let cats = [
  { 
    cat: "Actors",
    sel: false,
    parent: "",
    numOfItems: 0,
    items: ["EMIL JANNINGS", "WARNER BAXTER", "GEORGE ARLISS", "LIONEL BARRYMORE", "WALLACE BEERY", "FREDERIC MARCH", "CHARLES LAUGHTON", "CLARK GABLE", "VICTOR MCLAGLEN", "PAUL MUNI", "SPENCER TRACY", "ROBERT DONAT", "JAMES STEWART", "GARY COOPER", "JAMES CAGNEY", "PAUL LUKAS", "BING CROSBY", "RAY MILLAND", "RONALD COLEMAN", "LAURENCE OLIVIER", "BRODERICK CRAWFORD", "JOSE FERRER", "HUMPHREY BOGART", "GARY COOPER", "WILLIAM HOLDEN", "MARLON BRANDO", "ERNEST BORGNINE", "YUL BRYNNER", "ALEC GUINNESS", "DAVID NIVEN", "CHARLTON HESTON", "BURT LANCASTER", "MAXIMILLIAN SCHELL", "GREGORY PECK", "SIDNEY POITIER", "REX HARRISON", "LEE MARVIN", "PAUL SCOFIELD", "ROD STEIGER", "CLIFF ROBERTSON", "JOHN WAYNE", "GEORGE C SCOTT", "GENE HACKMAN", "JACK LEMMON", "ART CARNEY", "JACK NICHOLSON", "PETER FINCH", "RICHARD DREYFUSS", "JON VOIGHT", "DUSTIN HOFFMAN", "ROBERT DE NERO", "HENRY FONDA", "BEN KINGSLEY", "ROBERT DUVALL", "F MURRAY ABRAHAM", "WILLIAM HURT", "PAUL NEWMAN", "MICHAEL DOUGLAS", "DANIEL DAY LEWIS", "JEREMY IRONS", "ANTHONY HOPKINS", "AL PACINO", "TOM HANKS", "NICOLAS CAGE", "GEOFFREY RUSH", "ROBERTO BENIGNI", "KEVIN SPACEY", "RUSSELL CROWE", "DENZEL WASHINGTON", "ADRIEN BRODY", "SEAN PENN", "JAMIE FOXX", "PHILIP SEYMOUR HOFFMAN", "FOREST WHITAKER", "JEFF BRIDGES", "COLIN FIRTH", "JEAN DUJARDIN", "MATTHEW MCCONAUGHEY", "EDDIE REDMAYNE", "LEONARDO DICAPRIO", "CASEY AFFLECK", "GARY OLDMAN", "RAMI MALEK", "JOAQUIN PHOENIX", "ANTHONY HOPKINS", "WILL SMITH", "FRANCHOT TONE", "THOMAS MITCHELL", "CLAUDE RAINS", "PAUL HENRIED", "ERROL FLYNN", "CARY GRANT", "LEO G CARROLL", "JAMES MASON", "LOUIS HAYWARD", "HENRY DANIELL", "ROBERT TAYLOR", "WALTER HUSTON", "JOHN HUSTON", "RANDOLPH SCOTT", "WALTER BRENNAN", "WILLIAM POWELL", "VAN JOHNSON", "CHARLIE CHAPLIN", "LESLIE HOWARD", "RALPH BELLAMY", "RAYMOND MASSEY", "C AUBREY SMITH", "DOUGLAS FAIRBANKS JR", "FRED ASTAIRE", "BASIL RATHBONE", "TYRONE POWER", "DON AMECHE", "MICHAEL REDGRAVE", "BRIAN DONLEVY", "RALPH RICHARDSON", "EDWARD ARNOLD", "MELVYN DOUGLAS", "BELA LUGOSI", "BORIS KARLOFF", "CECIL KELLAWAY", "WARD BOND", "JOEL MCCREA", "ROBERT YOUNG", "VAN HEFLIN", "FRANK MORGAN", "CONRAD VEIDT", "WALTER PIDGEON", "RODDY MCDOWALL", "DONALD CRISP", "PETER LORRE", "SYDNEY GREENSTREET", "WARD BOND", "ELISHA COOK JR", "ROBERT MORLY", "REX HARRISON", "EDWARD G ROBINSON", "CEDRIC HARDWICKE", "NIGEL BRUCE", "KENT SMITH", "TOM CONWAY", "GEORGE SANDERS", "JOSEPH COTTEN", "ROBERT CUMMINGS", "OTTO KRUGER", "ALAN LADD", "JACK BENNY", "FRED MACMURRAY", "CHARLES BOYER", "BARRY FITZGERALD", "DANA ANDREWS", "CLIFTON WEBB", "VINCENT PRICE", "JOHN HODIAK", "WALTER SLEZAK", "WILLIAM BENDIX", "DICK POWELL", "MIKE MAZURKI", "MICKEY ROONEY", "GENE KELLY", "FRANK SINATRA", "CORNEL WILDE", "EDMOND OBRIEN", "JACK PALANCE", "ZERO MOSTEL", "RICHARD WIDMARK", "TOSHIRO MIFUNE", "ALASTAIR SIM", "MONTGOMERY CLIFT", "TREVOR HOWARD", "ROBERT RYAN", "EDMUND GWENN", "ROBERT MITCHUM", "DANNY KAYE", "GLENN FORD", "JOHN GARFIELD", "JAMES DEAN", "CLIFF ROBERTSON", "GORDON MACRAE", "PETER SELLERS", "VAN JOHNSON", "JOSE FERRER", "BROCK PETERS", "RICHARD CARLSON", "HUGH MARLOWE", "RAYMOND BURR", "LEE J COBB", "WENDELL COREY", "JOHN WILLIAMS", "MICHAEL RENNIE", "OSKAR WERNER", "FARLEY GRANGER", "JOHN GIELGUD", "TONY CURTIS", "ANTHONY PERKINS", "ELI WALLACH", "STEVE MCQUEEN", "CHARLES BRONSON", "JAMES COBURN", "ROBERT VAUGHN", "STEPHEN BOYD", "JACK HAWKINS", "HUGH GRIFFITH", "E G MARSHALL", "DEAN MARTIN", "PAUL NEWMAN", "SESSUE HAYAKAWA", "ANDY GRIFFITH", "ROBERT REDFORD", "DENNIS HOPPER", "NIGEL TERRY", "TIMOTHY DALTON", "GENE WILDER", "MICHAEL YORK", "JOHN CASSAVETES", "GEORGE KENNEDY", "STROTHER MARTIN", "PETER FINCH", "MICHAEL CAINE", "ROBERT SHAW", "LEO MCKERN", "JOHN HURT", "OMAR SHARIFF", "CHRISOPHER PLUMMER", "JAMES GARNER", "ANTHONY QUINN", "ROD TAYLOR", "ANGUS LENNIE", "DAVID MCCALLUM", "ALBERT FINNEY", "TERENCE STAMP", "PETER USTINOV", "LAURENCE HARVEY", "JAMES GREGORY","GEORGE PEPPARD", "RICHARD WIDMARK", "RICHARD GERE", "DENHOLM ELLIOTT", "SEAN CONNERY", "ROGER MOORE", "GEORGE LAZENBY", "CHIEF DAN GEORGE", "BURGESS MEREDITH", "ROY SCHEIDER", "SAEED JAFFREY", "ARNOLD SCHWARZENEGGER", "JOHNNY DEPP", "KEVIN COSTNER", "ED HARRIS", "MARTIN LANDAU", "KENNETH BRANAGH", "BILLY CRYSTAL"]
    },
  { 
    cat: "Actresses",
    sel: false,
    parent: "",
    numOfItems: 0,
    items: ["JANET GAYNOR", "MARY PICKFORD", "NORMA SHEARER", "MARIE DRESSLER", "HELEN HAYES", "KATHARINE HEPBURN", "CLAUDETTE COLBERT", "BETTE DAVIS", "LUISE RAINER", "VIVIEN LEIGH", "GINGER ROGERS", "JOAN FONTAINE", "GREER GARSON", "JENNIFER JONES", "INGRID BERGMAN", "JOAN CRAWFORD", "OLIVIA DE HAVILLAND", "LORETTA YOUNG", "JANE WYMAN", "JUDY HOLLIDAY", "SHIRLEY BOOTH", "AUDREY HEPBURN", "GRACE KELLY", "ANNA MAGNANI", "JOANNE WOODWARD", "SUSAN HAYWARD", "SIMONE SIGNORET", "ELIZABETH TAYLOR", "SOPHIA LOREN", "ANNE BANCROFT", "PATRICIA NEAL", "JULIE ANDREWS", "JULIE CHRISTIE", "BARBRA STREISAND", "MAGGIE SMITH", "GLENDA JACKSON", "JANE FONDA", "LIZA MINNELLI", "ELLEN BURSTYN", "LOUISE FLETCHER", "FAYE DUNAWAY", "DIANE KEATON", "SALLY FIELD", "SISSY SPACEK", "MERYL STREEP", "SHIRLEY MACLAINE", "GERALDINE PAGE", "MARLEE MATLIN", "CHER", "JODIE FOSTER", "JESSICA TANDY", "KATHY BATES", "EMMA THOMPSON", "HOLLY HUNTER", "JESSICA LANGE", "SUSAN SARANDON", "FRANCES MCDORMAND", "HELEN HUNT", "GWYNETH PALTROW", "HILARY SWANK", "JULIA ROBERTS", "HALLE BERRY", "NICOLE KIDMAN", "CHARLIZE THERON", "REESE WITHERSPOON", "HELEN MIRREN", "MARION COTILLARD", "KATE WINSLET", "SANDRA BULLOCK", "NATALIE PORTMAN", "JENNIFER LAWRENCE", "CATE BLANCHETT", "JULIANNE MOORE", "BRIE LARSON", "EMMA STONE", "OLIVIA COLMAN", "RENEE ZELLWEGER", "JESSICA CHASTAIN", "BARBARA BAIN", "GALE SONDERGAARD", "GRETA GARBO", "MARY ASTOR", "MADELEINE CARROLL", "MYRNA LOY", "ESTHER WILLIAMS", "LUCILLE BALL", "JEAN ARTHUR", "IRENE DUNNE", "BARBARA STANWYCK", "CONSTANCE BENNETT", "DAME MAY WHITTY", "MARGARET LOCKWOOD", "WENDY HILLER", "MARLENE DIETRICH", "EDNA MAY OLIVER", "HATTIE MCDANIEL", "MAUREEN OHARA", "CLAIRE TREVOR", "JUDY GARLAND", "MERLE OBERON", "FLORA ROBSON", "LARAINE DAY", "LINDA DARNELL", "MARGARET SULLAVAN", "JUDITH ANDERSON", "JUNE DUPREZ", "IDA LUPINO", "TERESA WRIGHT", "VERONICA LAKE", "CAROLE LOMBARD", "ELSA LANCHESTER", "AGNES MOOREHEAD", "GERALDIN FITZGERALD", "PRISCILLA LANE", "GENE TIERNEY", "TALLULAH BANKHEAD", "LAUREN BACALL", "ANNE BAXTER", "GLORIA SWANSON", "JOAN BENNETT", "SHIRLEY TEMPLE", "VIRGINIA MAYO", "JEAN SIMMONS", "RITA HAYWORTH", "DEBORAH KERR", "SIGNE HASSO", "NATALIE WOOD", "LANA TURNER", "MARILYN MONROE", "SUSAN HAYWARD", "ANGELA LANSBURY", "KIM HUNTER", "DEBBIE REYNOLDS", "GLORIA GRAHAME", "AVA GARDNER", "JANET LEIGH", "VERA MILES", "LEE REMICK", "HAYA HARAREET", "ANGIE DICKENSON", "ROSALIND RUSSELL", "JEAN SIMMONS", "KIM NOVAK", "AUDREY HEPBURN", "KATHARINE ROSS", "CLAUDIA CARDINALE", "PATTY DUKE", "VANESSA REDGRAVE", "HONOR BLACKMAN", "TIPPI HEDREN", "MARY BADHAM", "COLLIN WILCOX", "SIGOURNEY WEAVER", "SHARON STONE", "CLAIRE BLOOM", "MEG RYAN", "RAQUEL WELCH"]
    },
    { 
    cat: "Geo Features",
    sel: false,
    parent: "",
    numOfItems: 0,
    items: ["THE AMAZON", "THE NILE", "THE HUDSON", "THE SAHARA", "MT EVEREST", "THE GREAT SALT LAKE", "HIGH POINT", "THE ATLANTIC OCEAN", "THE PACIFIC OCEAN", "THE INDIAN OCEAN", "NORTH AMERICA", "EUROPE", "ASIA", "SOUTH AMERICA", "AFRICA", "MT WASHINGTON", "THE GOBI DESERT", "PIKES PEAK", "CRATER LAKE", "MT SAINT HELENS", "MT FUJI", "MT KILIMANJARO", "MT KENYA", "ACONGAGUA", "AMAZON RAIN FOREST", "DENALI", "MONT BLANC", "THE MATTERHORN", "THE JUNGFRAU", "THE EIGER", "THE THAMES", "THE SEINE", "THE DANUBE", "THE DNEIPER", "THE VOLGA","THE RIO GRANDE", "THE MISSISSIPPI", "THE MISSOURI", "ANTARCTICA", "THE GREAT BARRIER REEF", "NIAGARA FALLS", "ANGEL FALLS", "EL CAPITAN", "HALF DOME", "DEVILS TOWER", "MT RUSHMORE", "CATSKILLS", "ADIRONDACKS", "ROCKIES", "HIMALAYAS", "ANDES", "ALPS", "CARPATHIANS", "ATLAS", "AYERS ROCK", "EVERGLADES", "GREAT SMOKEY MOUNTAINS", "AFGHANISTAN", "ALBANIA", "ALGERIA", "ANDORRA", "ANGOLA", "ARGENTINA", "ARMENIA", "AUSTRALIA", "AUSTRIA", "AZERBAIJAN", "BAHAMAS", "BAHRAIN", "BANGLADESH", "BARBADOS", "BELARUS", "BELGIUM", "BELIZE", "BENIN", "BHUTAN", "BOLIVIA", "BOSNIA AND HERZEGOVINA", "BOTSWANA", "BRAZIL", "BRUNEI", "BULGARIA", "BURKINA FASO", "BURUNDI", "CAMBODIA", "CAMEROON", "CANADA", "CENTRAL AFRICAN REPUBLIC", "CHAD", "CHILE", "CHINA", "COLUMBIA", "CONGO REPUBLIC OF THE", "COSTA RICA", "COTE DIVOIRE", "CROATIA", "CUBA", "CYPRUS", "CZECH REPUBLIC", "DENMARK", "DJIBOUTI", "DOMINICA", "DOMINICAN REPUBLIC", "ECUADOR", "EGYPT", "EL SALVADOR", "EQUATORIAL GUINEA", "ERITREA", "ESTONIA", "ETHIOPIA", "FIJI", "FINLAND", "FRANCE", "GABON", "GAMBIA", "GEORGIA", "GERMANY", "GHANA", "GREECE", "GRENADA", "GUATEMALA", "GUYANA", "HAITI", "HONDURAS", "HUNGARY", "ICELAND", "INDONESIA", "INDIA", "IRAN", "IRAQ", "IRELAND", "ISRAEL", "ITALY", "JAMAICA", "JAPAN", "JORDAN","KAZAKHSTAN", "KENYA", "KOSOVO", "KUWAIT", "KYRGYZSTAN", "LAOS", "LATVIA", "LEBANON", "LESOTHO", "LIBERIA", "LIBYA", "LIECHTENSTEIN", "LITHUANIA", "LUXEMBOURG", "MADAGASCAR", "MALAWI", "MALAYSIA", "MALDIVES", "MALI", "MALTA", "MARSHALL ISLANDS", "MAURITANIA", "MAURITIUS", "MEXICO", "MICRONESIA", "MOLDOVA", "MONACO", "MONTENEGRO", "MOROCCO", "MOZAMBIQUE", "MYANMAR", "NAMIBIA", "NEPAL", "NETHERLANDS", "NEW ZEALAND", "NICARAGUA", "NIGER", "NIGERIA", "NORTH KOREA", "NORTH MACEDONIA", "NORWAY", "OMAN", "PAKISTAN", "PALESTINE","PANAMA", "PAPUA NEW GUINEA", "PARAGUAY", "PERU", "PHILIPPINES", "POLAND", "PORTUGAL", "QATAR", "ROMANIA", "RUSSIA", "RWANDA", "SAINT KITTS AND NEVIS", "SAINT LUCIA", "SAINT VINCENT AND THE GRENADINES", "SAMOA", "SAN MARINO", "SAUDI ARABIA", "SENEGAL", "SERBIA", "SEYCHELLES", "SIERRA LEONE", "SINGAPORE", "SLOVAKIA", "SLOVENIA", "SOLOMON ISLANDS", "SOMALIA", "SOUTH AFRICA", "SOUTH KOREA", "SOUTH SUDAN", "SPAIN", "SRI LANKA", "SUDAN", "SURINAME", "SWEDEN", "SWITZERLAND", "SYRIA", "TAIWAN", "TAJIKISTAN", "TANZANIA", "THAILAND", "TOGO", "TONGA", "TRINIDAD AND TOBAGO", "TUNISIA", "TURKEY", "TURKMENISTAN", "TUVALU", "UGANDA","UKRAINE", "UNITED ARAB EMIRATES", "UNITED KINGDOM", "UNITED STATES OF AMERICA", "URUGUAY", "UZBEKISTAN", "VATICAN CITY", "VENEZUELA", "VIETNAM", "YEMEN", "ZAMBIA", "ZIMBABWE", "ALABAMA", "ALASKA", "ARIZONA", "ARKANSAS", "CALIFORNIA", "COLORADO", "CONNECTICUT", "DELAWARE", "FLORIDA", "GEORGIA", "HAWAII", "IDAHO", "ILLINOIS", "INDIANA", "IOWA", "KANSAS", "KENTUCKY", "LOUISIANA", "MAINE", "MARYLAND", "MASSACHUSETTS", "MICHIGAN", "MINNESOTA", "MISSISSIPPI", "MISSOURI", "MONTANA", "NEBRASKA", "NEVADA", "NEW HAMPSHIRE", "NEW JERSEY", "NEW MEXICO", "NEW YORK", "NORTH CAROLINA", "NORTH DAKOTA", "OHIO", "OKLAHOMA", "OREGON", "PENNSYLVANIA", "RHODE ISLAND", "SOUTH CAROLINA", "SOUTH DAKOTA", "TENNESSEE", "TEXAS", "UTAH", "VERMONT", "VIRGINIA", "WASHINGTON", "WEST VIRGINIA", "WISCONSIN", "WYOMING", "MONTGOMERY", "JUNEAU", "PHOENIX", "LITTLE ROCK", "SACRAMENTO", "DENVER", "HARTFORD", "DOVER", "TALLAHASSEE", "ATLANTA", "HONOLULU", "BOISE", "SPRINGFIELD", "INDIANAPOLIS", "DES MOINES", "TOPEKA", "FRANKFORT", "BATON ROUGE", "AUGUSTA", "ANNAPOLIS", "BOSTON", "LANSING", "ST PAUL", "JACKSON", "JEFFERSON CITY", "HELENA", "LINCOLN", "CARSON CITY", "CONCORD", "TRENTON", "SANTA FE", "ALBANY", "RALEIGH", "BISMARK", "COLUMBUS", "OKLAHOMA CITY", "SALEM", "HARRISBURG", "PROVIDENCE", "COLUMBIA", "PIERRE", "NASHVILLE", "AUSTIN", "SALT LAKE CITY", "MONTPELIER", "RICHMOND", "OLYMPIA", "CHARLESTON", "MADISON", "CHEYENNE", "MOBILE", "ANCHORAGE", "SCOTTSDALE", "LOS ANGELES", "SAN DIEGO", "SAN FRANCISCO", "SAN JOSE", "BOULDER", "ASPEN", "VAIL", "DURANGO", "BETHLEHEM", "NEW LONDON", "NEW HAVEN", "WILMINGTON", "MIAMI", "TAMPA BAY", "ORLANDO", "AUGUSTA", "HILO", "CHICAGO", "PEORIA", "GARY", "LEXINGTON", "NEW ORLEANS", "BANGOR", "PORTLAND", "KENNEBUNKPORT", "BALTIMORE", "SPRINGFIELD", "ANN ARBOR", "MINNEAPOLIS", "BILOXI", "KANSAS CITY", "ST LOUIS", "RENO", "LAS VEGAS", "MANCHESTER", "MORRISTOWN", "PARAMUS", "ALBUQUERQUE", "NEW YORK CITY", "SYRACUSE", "CHARLOTTE", "COLUMBUS", "CINCINNATI", "CLEVELAND", "PITTSBURGH", "PHILADELPHIA", "NEWPORT", "CHARLESTON", "NASHVILLE", "MEMPHIS", "HOUSTON", "DALLAS", "EL PASO", "PROVO", "ALEXANDRIA", "ROANOKE", "SEATTLE", "TACOMA", "WHEELING", "GREEN BAY", "MILWAUKEE", "JACKSON HOLE", "SAN ANTONIO", "JACKSONVILLE", "FORT WORTH", "DETROIT", "LOUISVILLE", "FRESNO", "TUCSON", "OMAHA", "COLORADO SPRINGS", "VIRGINIA BEACH", "WICHITA", "ANAHEIM", "CORPUS CHRISTI", "NEWARK", "GREENSBORO", "JERSEY CITY", "BUFFALO", "TOLEDO", "ST PETERSBURG", "NORFOLK", "TACOMA", "ROCHESTER", "YONKERS", "FAYETTEVILLE", "NEWPORT NEWS", "TEMPE", "SHREVEPORT", "FORT LAUDERDALE", "FARGO", "ALLENTOWN", "WATERBURY", "WOODBRIDGE", "NEW BEDFORD", "KABUL", "TIRANA", "ALGIERS", "ANDORRA LA VELLA", "LUANDA", "BUENOS AIRES", "YEREVAN", "CANBERRA", "VIENNA", "BAKU", "NASSAU", "DHAKA", "MINSK", "BRUSSELS", "LA PAZ", "SARAJEVO", "BRASILIA", "SOFIA", "PHNOM PENH", "OTTAWA", "SANTIAGO", "BEIJING", "BOGOTA", "KINSHASA", "BRAZZAVILLE", "SAN JOSE", "ZAGREB", "HAVANA", "NICOSIA", "PRAGUE", "COPENHAGEN", "SANTO DOMINGO", "QUITO", "CAIRO", "SAN SALVADOR", "TALLINN", "ADDIS ABABA","HELSINKI", "PARIS", "TBILISI", "BERLIN", "ATHENS", "GUATEMALA CITY", "PORT AU PRINCE", "BUDAPEST", "REYKJAVIK", "NEW DELHI", "JAKARTA", "TEHRAN", "BAGHAD", "DUBLIN", "JERUSALEM", "ROME", "KINGSTON", "TOKYO", "AMMAN", "NAIROBI", "PRISTINA", "KUWAIT CITY", "VIENTIANE", "RIGA", "BEIRUT", "MONROVIA", "TRIPOLI", "VADUZ", "VILNIUS", "LUXEMBOURG", "KUALA LUMPUR", "MEXICO CITY", "ULAANBAATAR", "RABAT", "KATHMANDU", "AMSTERDAM", "WELLINGTON", "MANAGUA", "PYONGYANG", "OSLO", "MUSCAT", "ISLAMABAD", "PANAMA CITY", "ASUNCION", "LIMA", "MANILA", "WARSAW", "LISBON", "BUCHAREST", "MOSCOW", "RIYADH", "DAKAR", "EDINBURGH", "BELGRADE", "BRATISLAVA", "LJUBLJANA", "MOGADISHU", "CAPE TOWN", "SEOUL", "MADRID", "KHARTOUM", "STOCKHOLM", "BERN", "DAMASCUS", "TAIPEI", "BANGKOK", "TUNIS", "ANKARA", "KAMPALA", "KYIV", "KIEV", "ABU DHABI", "LONDON", "WASHINGTON DC", "MONTEVIDEO", "TASHKENT","CARACAS", "HANOI", "RIO DE JANEIRO", "MELBOURNE", "SYDNEY", "ADELAIDE", "PERTH", "INNSBRUCK", "SALZBURG", "GHENT", "BRUGES", "SAO PAOLO", "MONTREAL", "QUEBEC", "TORONTO", "CALGARY", "WINNIPEG", "VANCOUVER", "SHANGHAI", "ALEXANDRIA", "MARSEILLE", "MUNICH", "POTSDAM", "DUSSELDORF", "HAMBURG", "FRANKFURT", "MUMBAI", "CALCUTTA", "TEL AVIV", "BETHLEHEM", "FLORENCE", "MILAN", "VENICE", "YOKOHAMA", "KYOTO", "OSAKA", "ACAPULCO", "CASABLANCA", "ROTTERDAM", "THE HAGUE", "CHRISTCHURCH", "KARACHI", "ISTANBUL", "KHARKOV", "LVIV", "LVOV", "MANCHESTER", "LIVERPOOL", "OXFORD", "CAMBRIDGE", "ABERDEEN", "GLASGOW", "ZURICH", "GENEVA", "INTERLAKEN", "LUCERNE", "BARCELONA", "ALEXANDRIA", "SAINT PETERSBURG", "SAPPORO", "DAMASCUS", "NAPLES", "MECCA", "HIROSHIMA", "TURIN", "AUKLAND", "ANTWERP"]
    },  
    { 
    cat: "Movies",
    sel: false,
    parent: "",
    numOfItems: 0,
    items: ["WINGS", "THE BROADWAY MELODY", "CIMMARON", "GRAND HOTEL",  "CAVALCADE", "IT HAPPENED ONE NIGHT", "MUTINY ON THE BOUNTY", "THE GREAT ZIEGFELD", "THE LIFE OF EMILE ZOLA", "GONE WITH THE WIND", "REBECCA", "HOW GREEN WAS VALLEY", "MRS MINIVER", "CASABLANCA", "GOING MY WAY", "THE LOST WEEKEND", "GENTLEMANS AGREEMENT", "HAMLET", "ALL THE KINGS MEN", "ALL ABOUT EVE", "AN AMERICAN IN PARIS", "THE GREATEST SHOW ON EARTH", "FROM HERE TO ETERNITY", "ON THE WATERFRONT", "MARTY", "THE BRIDGE ON THE RIVER KWAI", "GIGI", "BEN HUR", "THE APARTMENT", "WEST SIDE STORY", "LAWRENCE OF ARABIA", "TOM JONES", "MY FAIR LADY", "THE SOUND OF MUSIC", "A MAN FOR ALL SEASONS", "IN THE HEAT OF THE NIGHT", "OLIVER", "MIDNIGHT COWBOY", "PATTON", "THE FRENCH CONNECTION", "THE GODFATHER", "THE STING", "THE GODFATHER PART II", "ROCKY", "ANNIE HALL", "THE DEER HUNTER", "KRAMER VS KRAMER", "ORDINARY PEOPLE", "CHARIOTS OF FIRE", "GANDHI", "TERMS OF ENDEARMENT", "AMADEUS", "OUT OF AFRICA", "PLATOON", "THE LAST EMPEROR", "RAIN MAN", "DRIVING MISS DAISY", "DANCES WITH WOLVES", "THE SILENCE OF THE LAMBS", "UNFORGIVEN", "SCHINDLERS LIST", "FORREST GUMP", "BRAVEHEART", "THE ENGLISH PATIENT", "TITANIC", "SHAKESPEARE IN LOVE", "AMERICAN BEAUTY", "GLADIATOR", "A BEAUTIFUL MIND", "CHICAGO", "LORD OF THE RINGS", "MILLION DOLLAR BABY", "CRASH", "THE DEPARTED", "NO COUNTRY FOR OLD MEN", "SLUMDOG MILLIONAIRE", "THE HURT LOCKER", "THE KINGS SPEECH", "THE ARTIST", "ARGO", "TWELVE YEARS A SLAVE", "BIRDMAN", "SPOTLIGHT", "MOONLIGHT", "THE SHAPE OF WATER", "GREEN BOOK", "PARASITE", "NOMADLAND", "CODA", "MODERN TIMES", "THE PETRIFIED FOREST", "THE GOOD EARTH", "LOST HORIZON", "THE PRISONER OF ZENDA", "TOPPER", "THE ADVENTURES OF ROBIN HOOD", "BRINGING UP BABY", "THE LADY VANISHES", "YOU CANT TAKE IT WITH YOU", "DESTRY RIDES AGAIN", "THE FOUR FEATHERS", "GOODBYE MR CHIPS", "GUNGA DIN", "THE HUNCHBACK OF NOTRE DAME", "MR SMITH GOES TO WASHINGTON", "NINOTCHKA", "STAGECOACH", "THE WIZARD OF OZ", "WUTHERING HEIGHTS", "ABE LINCOLN IN ILLINOIS", "FANTASIA", "FOREIGN CORRESPONDENT", "THE GRAPES OF WRATH", "THE GREAT DICTATOR", "HIS GIRL FRIDAY", "THE MARK OF ZORRO", "THE PHILADELPHIA STORY", "PRIDE AND PREJUDICE", "REBECCA", "THE SEA HAWK", "THE SHOP AROUND THE CORNER", "THE THIEF OF BAGDAD", "CITIZEN KANE", "HERE COMES MR JORDAN", "HIGH SIERRA", "HOW GREEN WAS MY VALLEY", "THE MALTESE FALCON", "MEET JOHN DOE", "THE SEA WOLF", "SERGEANT YORK", "SUSPICION", "THAT HAMILTON WOMAN", "THE WOLF MAN", "CASABLANCA", "KINGS ROW", "THE MAGNIFICENT AMBERSONS", "NOW VOYAGER", "THE PRIDE OF THE YANKEES", "RANDOM HARVEST", "SABOTEUR", "TO BE OR NOT TO BE", "FOR WHOM THE BELL TOLLS", "HEAVEN CAN WAIT", "JANE EYRE", "THE OX BOW INCIDENT", "PHANTOM OF THE OPERA", "SHADOW OF A DOUBT", "THE SONG OF BERNADETTE", "WATCH ON THE RHINE", "ARSENIC AND OLD LACE", "DOUBLE INDEMNITY", "GASLIGHT", "GOING MY WAY", "HENRY V", "LAURA", "LIFEBOAT", "MEET ME IN ST LOUIS", "MURDER MY SWEET", "NATIONAL VELVET", "TO HAVE AND HAVE NOT", "AND THEN THERE WERE NONE", "THE BELLS OF ST MARYS", "THE BODY SNATCHER", "LEAVE HER TO HEAVEN", "MILDRED PIERCE", "THE PICTURE OF DORIAN GRAY", "SPELLBOUND", "A TREE GROWS IN BROOKLYN", "THE BEST YEARS OF OUR LIVES", "THE BIG SLEEP", "ITS A WONDERFUL LIFE", "MY DARLING CLEMENTINE", "NOTORIOUS", "THE POSTMAN ALWAYS RINGS TWICE", "THE SPIRAL STAIRCASE", "THE STRANGER", "THE YEARLING", "THE BACHELOR AND THE BOBBY SOXER", "THE BISHOPS WIFE", "BLACK NARCISSUS", "CROSSFIRE", "DARK PASSAGE", "A DOUBLE LIFE", "THE FARMERS DAUGHTER", "GENTLEMANS AGREEMENT", "THE GHOST AND MRS MUIR", "THE SECRET LIFE OF WALTER MITTY", "I REMEMBER MAMA", "JOHNNY BELINDA", "KEY LARGO", "THE LADY FROM SHANGHAI", "RED RIVER", "THE RED SHOES", "ROPE", "THE SNAKE PIT", "THE TREASURE OF THE SIERRA MADRE", "ALL THE KINGS MEN", "THE FOUNTAINHEAD", "THE HEIRESS", "KIND HEARTS AND CORONETS", "ON THE TOWN", "SHE WORE A YELLOW RIBBON", "THE THIRD MAN", "TWELVE OCLOCK HIGH", "WHITE HEAT", "ALL ABOUT EVE", "THE ASPHALT JUNGLE", "BORN YESTERDAY", "FATHER OF THE BRIDE", "HARVEY", "RASHOMON", "SUNSET BOULEVARD", "THE AFRICAN QUEEN", "AN AMERICAN IN PARIS", "A CHRISTMAS CAROL", "THE DAY THE EARTH STOOD STILL", "A PLACE IN THE SUN", "QUO VADIS", "STRANGERS ON A TRAIN", "A STREETCAR NAMED DESIRE", "THE THING", "THE GREATEST SHOW ON EARTH", "HIGH NOON", "THE QUIET MAN", "SINGIN IN THE RAIN", "I CONFESS", "JULIUS CAESAR", "NIAGARA", "THE ROBE", "ROMAN HOLIDAY", "SHANE", "THE WAR OF THE WORLDS", "THE CAINE MUTINY", "CREATURE FROM THE BLACK LAGOON", "DIAM M FOR MURDER", "THE FAR COUNTRY", "GODZILLA", "REAR WINDOW", "SABRINA", "A STAR IS BORN", "BAD DAY AT BLACK ROCK", "BLACKBOARD JUNGLE", "THE COURT JESTER", "EAST OF EDEN", "GUYS AND DOLLS", "THE LADYKILLERS", "MISTER ROBERTS", "OKLAHOMA", "PICNIC", "REBEL WITHOUT A CAUSE", "RICHARD III", "TO CATCH A THIEF", "ANASTASIA", "FRIENDLY PERSUASION", "GIANT", "HIGH SOCIETY", "INVASION OF THE BODY SNATCHERS", "THE KING AND I", "THE MAN WHO KNEW TOO MUCH", "MOBY DICK", "THE SEARCHERS", "THE TEN COMMANDMENTS", "AN AFFAIR TO REMEMBER", "A FACE IN THE CROWD", "GUNFIGHT AT THE OK CORRAL", "THE INCREDIBLE SHRINKING MAN", "PATHS OF GLORY", "THE THREE FACES OF EVE", "TWELVE ANGRY MEN", "WILD STRAWBERRIES", "WITNESS FOR THE PROSECUTION", "AUNTIE MAME", "THE BIG COUNTRY", "TOUCH OF EVIL", "VERTIGO", "ANATOMY OF A MURDER", "NORTH BY NORTHWEST", "RIO BRAVO", "SOME LIKE IT HOT", "ELMER GANTRY", "INHERIT THE WIND", "THE MAGNIFICENT SEVEN", "PSYCHO", "SPARTACUS", "THE SUNDOWNERS", "BREAKFAST AT TIFFANYS", "THE GUNS OF NAVARONE", "JUDGEMENT AT NUREMBURG", "SPLENDOR IN THE GRASS", "BILLY BUDD", "CAPE FEAR", "DR NO", "HOW THE WEST WAS WON", "LOLITA", "THE LONGEST DAY", "THE MAN WHO SHOT LIBERTY VALANCE", "THE MANCHURIAN CANDIDATE", "THE MIRACLE WORKER", "TO KILL A MOCKINGBIRD", "WHAT EVER HAPPENED TO BABY JANE", "THE BIRDS", "BYE BYE BIRDIE", "CHARADE", "FROM RUSSIA WITH LOVE", "THE HAUNTING", "LILIES OF THE FIELD", "THE NUTTY PROFESSOR", "THE PINK PANTHER", "TOM JONES", "DR STRANGELOVE", "FAIL SAFE", "GOLDFINGER", "A HARD DAYS NIGHT", "MARNIE", "MARY POPPINS", "MY FAIR LADY", "THE NIGHT OF THE IGUANA", "THE PAWNBROKER", "A SHOT IN THE DARK", "ZORBA THE GREEK", "ZULU", "DOCTOR ZHIVAGO", "HELP", "BORN FREE", "FANTASTIC VOYAGE", "BONNIE AND CLYDE", "COOL HAND LUKE", "THE DIRTY DOZEN", "THE GRADUATE", "GUESS WHOS COMING TO DINNER", "IN THE HEAT OF THE NIGHT", "WAIT UNTIL DARK", "BULLIT", "CHARLY", "FUNNY GIRL", "THE LION IN WINTER", "NIGHT OF THE LIVING DEAD", "PLANET OF THE APES", "THE PRODUCERS", "ROSEMARYS BABY", "THE THOMAS CROWN AFFAIR", "BUTCH CASSIDY AND THE SUNDANCE KID", "EASY RIDER", "THE PRIME OF MISS JEAN BRODIE", "TRUE GRIT", "THE WILD BUNCH", "FIVE EASY PIECES", "A CLOCKWORK ORANGE", "DEATH IN VENICE", "DIRTY HARRY", "FIDDLE ON THE ROOF", "HAROLD AND MAUDE", "THE LAST PICTURE SHOW", "NICHOLAS AND ALEXANDRA", "PLAY MISTY FOR ME", "SHAFT", "SUNDAY BLOODY SUNDAY", "CABARET", "DELIVERANCE", "FRENZY", "LAST TANGO IN PARIS", "SLEUTH", "SOUNDER", "SUPER FLY", "AMERICAN GRAFFITI", "THE DAY OF THE JACKAL", "ENTER THE DRAGON", "THE EXORCIST", "HIGH PLAINS DRIFTER", "MEAN STREETS", "THE PAPER CHASE", "PAPER MOON", "PAPILLON", "SERPICO", "SLEEPER", "BLAZING SADDLES", "CHINATOWN", "THE CONVERSATION", "HARRY AND TONTO", "THE TOWERING INFERNO", "YOUNG FRANKENSTEIN", "BARRY LYNDON", "DOG DAY AFTERNOON", "JAWS", "THE MAN WHO WOULD BE KING", "MONTY PYTHON AND THE HOLY GRAIL", "ALL THE PRESIDENTS MEN", "MARATHON MAN", "NETWORK", "THE OMEN", "TAXI DRIVER", "CLOSE ENCOUNTERS OF THE THIRD KIND", "SATURDAY NIGHT FEVER", "THE SPY WHO LOVED ME", "STAR WARS", "COMING HOME", "MIDNIGHT EXPRESS", "WATERSHIP DOWN", "ALIEN", "APOCALYPSE NOW", "BEING THERE", "THE CHINA SYNDROME", "NORMA RAE", "RAGING BULL", "THE SHINING", "ARTHUR", "BODY HEAT", "DAS BOOT", "GALLIPOLI", "THE ROAD WARRIOR", "MY DINNER WITH ANDRE", "RAGTIME", "RAIDERS OF THE LOST ARK", "BLADE RUNNER", "DINER", "E T THE EXTRA TERRESTRIAL", "AN OFFICER AND A GENTLEMAN", "POLTERGEIST", "SOPHIES CHOICE", "TOOTSIE", "THE VERDICT", "THE BIG CHILL", "A CHRISTMAS STORY", "FLASHDANCE", "RETURN OF THE JEDI", "THE RIGHT STUFF", "RISKY BUSINESS", "SUDDEN IMPACT", "TENDER MERCIES", "GHOSTBUSTERS", "THE KILLING FIELDS", "THE NATURAL", "A PASSAGE TO INDIA", "ROMANCING THE STONE", "THE TERMINATOR", "THIS IS SPINAL TAP", "BACK TO THE FUTURE", "THE BREAKFAST CLUB", "THE COLOR PURPLE", "PALE RIDER", "PRIZZIS HONOR", "A ROOM WITH A VIEW", "WITNESS", "ALIENS", "CHILDREN OF A LESSER GOD", "THE COLOR OF MONEY", "CROCODILE DUNDEE", "THE FLY", "HANNAH AND HER SISTERS", "THE MISSION", "PLATOON", "STAND BY ME", "TOP GUN", "DIRTY DANCING", "FATAL ATTRACTION", "FULL METAL JACKET", "GOOD MORNING VIETNAM", "THE LAST EMPEROR", "LETHAL WEAPON", "MOONSTRUCK", "PREDATOR", "THE PRINCESS BRIDE", "SUSPECT", "THE UNTOUCHABLES", "THE ACCIDENTAL TOURIST", "BULL DURHAM", "CINEMA PARDISO", "DANGEROUS LIAISONS", "DIE HARD", "A FISH CALLED WANDA", "MISSISSIPPI BURNING", "WHO FRAMED ROGER RABBIT", "THE ABYSS", "BATMAN", "BORN ON THE FOURTH OF JULY", "DEAD POETS SOCIETY", "DO THE RIGHT THING", "DRIVING MISS DAISY", "FIELD OF DREAMS", "GLORY", "HENRY V", "MY LEFT FOOT", "WHEN HARRY MET SALLY", "AWAKENINGS", "DANCES WITH WOLVES", "EDWARD SCISSORHANDS", "GOODFELLAS", "HOME ALONE", "PRESUMED INNOCENT", "PRETTY WOMAN", "REVERSAL OF FORTUNE", "TOTAL RECALL", "CITY SLICKERS", "FRIED GREEN TOMATOS", "THELMA AND LOUISE", "ALADDIN", "BASIC INSTINCT", "A FEW GOOD MEN", "THE LAST OF THE MOHICANS", "MY COUSIN VINNY", "MALCOLM X", "A RIVER RUNS THROUGH IT", "SCENT OF WOMAN", "THE FUGITIVE", "GROUNDHOG DAY", "IN THE NAME OF THE FATHER", "THE JOY LUCK CLUB", "JURASSIC PARK", "MRS DOUBTFIRE", "PHILADELPHIA", "THE PIANO", "THE REMAINS OF THE DAY", "SLEEPLESS IN SEATTLE", "HOOP DREAMS", "THE LION KING", "THE MADNESS OF KING GEORGE", "PULP FICTION", "THE SHAWSHANK REDEMPTION", "TRIAL BY JURY", "TRUE LIES", "THE BRIDGES OF MADISON COUNTY", "CASINO", "GOLDENEYE", "LEAVING LAS VEGAS", "SENSE AND SENSIBILITY", "TOY STORY", "DR NO", "FROM RUSSIA WITH LOVE", "THUNDERBALL", "DIAMONDS ARE FOREVER", "YOU ONLY LIVE TWICE", "ON HER MAJESTYS SECRET SERVICE", "LIVE AND LET DIE", "THE SPY WHO LOVED ME", "FOR YOUR EYES ONLY", "A VIEW TO A KILL", "THE LIVING DAYLIGHTS", "LICENSE TO KILL", "THE MAN WITH THE GOLDEN GUN", "THE SPY WHO LOVED ME", "MOONRAKER", "OCTOPUSSY", "NEVER SAY NEVER AGAIN", "FARGO", "INDEPENDENCE DAY", "JERRY MAGUIRE", "TWISTER", "AMISTAD", "GOOD WILL HUNTING", "TITANIC", "THE BIG LEBOWSKI", "SAVING PRIVATE RYAN", "THERES SOMETHING ABOUT MARY", "BEING JOHN MALKOVICH", "THE BLAIR WITCH PROJECT", "THE MATRIX", "THE SIXTH SENSE", "CROUCHING TIGER HIDDEN DRAGON", "ERIN BROCKOVICH"]
    },
    {
      cat: "Beatles Songs",
      sel: false,
      parent: "Music",
      numOfItems: 0,
      items: ["I SAW HER STANDING THERE", "MISERY", "LOVE ME DO", "PS I LOVE YOU", "DO YOU WANT TO KNOW A SECRET", "A TASTE OF HONEY", "TWIST AND SHOUT", "I WANT TO HOLD YOUR HAND", "THIS BOY", "IT WONT BE LONG", "ALL IVE GOT TO DO", "ALL MY LOVING", "DONT BOTHER ME", "LITTLE CHILD", "TIL THERE WAS YOU", "HOLD ME TIGHT", "I WANNA BE YOUR MAN", "NOT A SECOND TIME", "THANK YOU GIRL", "YOU REALLY GOT A HOLD ON ME", "MONEY", "YOU CANT DO THAT", "LONG TALL SALLY", "I CALL YOUR NAME", "PLEASE MR POSTMAN", "ILL GET YOU", "SHE LOVES YOU", "A HARD DAYS NIGHT", "TELL ME WHY", "ILL CRY INSTEAD", "I SHOULD HAVE KNOWN BETTER", "AND I LOVE HER", "IF I FELL", "CANT BUY ME LOVE", "THINGS WE SAID TODAY", "ANY TIME AT ALL", "MATCHBOX", "SLOW DOWN", "TELL ME WHY", "NO REPLY", "IM A LOSER", "BABYS IN BLACK", "ROCK AND ROLL MUSIC", "ILL FOLLOW THE SUN", "MR MOONLIGHT", "HONEY DONT", "ILL BE BACK", "SHES A WOMAN", "I FEEL FINE", "PLEASE PLEASE ME", "EIGHT DAYS A WEEK", "WORDS OF LOVE", "YES IT IS", "DIZZY MISS LIZZY", "HELP", "I NEED YOU", "ANOTHER GIRL", "TICKET TO RIDE", "YOURE GOING TO LOSE THAT GIRL", "IVE JUST SEEN A FACE", "NORWEGIAN WOOD", "THINK FOR YOURSELF", "MICHELLE", "GIRL", "IN MY LIFE", "WAIT", "DRIVE MY CAR", "NOWHERE MAN", "YESTERDAY", "ACT NATURALLY", "WE CAN WORK IT OUT", "DAY TRIPPER", "ELEANOR RIGBY", "YELLOW SUBMARINE", "GOOD DAY SUNSHINE", "SHES LEAVING HOME", "WHEN IM SIXTY FOUR", "LOVELY RITA", "A DAY IN THE LIFE", "MAGICAL MYSTERY TOUR", "THE FOOL ON THE HILL", "BLUE JAY WAY", "I AM THE WALRUS", "HELLO GOODBYE", "STRAWBERRY FIELDS FOREVER", "PENNY LANE", "BABY YOURE A RICH MAN", "ALL YOU NEED IS LOVE", "BACK IN THE USSR", "OB LA DI OB LA DA", "BLACKBIRD", "ROCKY RACCOON", "DONT PASS ME BY", "JULIA", "YELLOW SUBMARINE", "ALL TOGETHER NOW", "COME TOGETHER", "SOMETHING", "HERE COMES THE SUN", "REVOLUTION", "HEY JUDE", "ACROSS THE UNIVERSE", "LET IT BE"]
      }, 
  { 
    cat: "Hits of the 60's",
    sel: false,
    parent: "Music",
    numOfItems: 0,
    items: ["EL PASO", "RUNNING BEAR", "TEEN ANGEL", "THEME FROM A SUMMER PLACE", "CATHYS CLOWN", "ITS NOW OR NEVER", "THE TWIST", "SAVE THE LAST DANCE FOR ME", "GEORGIA ON MY MIND", "STAY", "ARE YOU LONESOME TONIGHT", "WILL YOU LOVE ME TOMORROW", "BLUE MOON", "RUNAWAY", "MOTHER IN LAW", "TRAVELIN MAN", "TOSSIN AND TURNIN", "MICHAEL", "TAKE GOOD CARE OF MY BABY", "HIT THE ROAD JACK", "RUNAROUND SUE", "BIG BAD JOHN", "PLEASE MR POSTMAN", "THE LION SLEEPS TONIGHT", "DUKE OF EARL", "JOHNNY ANGEL", "SOLDIER BOY", "I CANT STOP LOVING YOU", "ROSES ARE RED", "BREAKING UP IS HARD TO DO", "THE LOCO MOTION", "SHERRY", "MONSTER MASH", "HES A REBEL", "BIG GIRLS DONT CRY", "GO AWAY LITTLE GIRL", "WALK RIGHT IN", "HEY PAULA", "WALK LIKE A MAN", "OUR DAY WILL COME", "HES SO FINE", "I WILL FOLLOW HIM", "ITS MY PARTY", "EASIER SAID THAN DONE", "SURF CITY", "MY BOYFRIENDS BACK", "BLUE VELVET", "DOMINIQUE", "I WANT TO HOLD YOUR HAND", "SHE LOVES YOU", "CANT BUY ME LOVE", "HELLO DOLLY", "MY GUY", "LOVE ME DO", "CHAPEL OF LOVE", "A WORLD WITHOUT LOVE", "I GET AROUND", "RAG DOLL", "A HARD DAYS NIGHT", "EVERYBODY LOVES SOMEBODY", "WHERE DID OUR LOVE GO", "THE HOUSE OF THE RISING SUN", "OH PRETTY WOMAN", "DO WAH DIDDY DIDDY", "BABY LOVE", "LEADER OF THE PACK", "RINGO", "MR LONELY", "COME SEE ABOUT ME", "I FEEL FINE", "DOWNTOWN", "YOUVE LOST THAT LOVIN FEELING", "THIS DIAMOND RING", "MY GIRL", "EIGHT DAYS A WEEK", "STOP IN THE NAME OF LOVE", "IM TELLING YOU NOW", "MRS BROWN YOUVE GOT A LOVELY DAUGHTER", "TICKET TO RIDE",
      "HELP ME RHONDA", "BACK IN MY ARMS AGAIN", "I CANT HELP MYSELF", "MR TAMBOURINE MAN", "SATISFACTION", "IM HENRY VIII I AM", "I GOT YOU BABE", "HELP", "EVE OF DESTRUCTION", "HANG ON SLOOPY", "YESTERDAY", "GET OFF MY CLOUD", "I HEAR A SYMPHONY", "TURN TURN TURN", "OVER AND OVER", "THE SOUND OF SILENCE", "WE CAN WORK IT OUT", "MY LOVE", "LIGHTNIN STRIKES", "THESE BOOTS ARE MADE FOR WALKIN", "THE BALLAD OF THE GREEN BERETS", "SOUL AND INSPIRATION", "GOOD LOVIN", "MONDAY MONDAY", "WHEN A MAN LOVES A WOMAN", "PAINT IT BLACK", "PAPERBACK WRITER", "STRANGERS IN THE NIGHT", "HANKY PANKY", "WILD THING", "SUMMER IN THE CITY", "SUNSHINE SUPERMAN", "YOU CANT HURRY LOVE", "CHERISH", "REACH OUT ILL BE THERE", "LAST TRAIN TO CLARKSVILLE", "YOU KEEP ME HANGIN ON", "WINCHESTER CATHEDRAL", "GOOD VIBRATIONS", "IM A BELIEVER", "KIND OF A DRAG", "PENNY LANE", "HAPPY TOGETHER", "SOMETHIN STUPID", "THE HAPPENING", "GROOVIN", "RESPECT", "WINDY", "LIGHT MY FIRE", "ALL YOU NEED IS LOVE", "ODE TO BILLIE JOE", "THE LETTER", "TO SIR WITH LOVE", "INCENSE AND PEPPERMINTS", "DAYDREAM BELIEVER", "HELLO GOODBYE", "JUDY IN DISGUISE", "GREEN TAMBOURINE", "LOVE IS BLUE", "THE DOCK OF THE BAY", "HONEY", "TIGHTEN UP", "MRS ROBINSON", "THIS GUYS IN LOVE WITH YOU", "GRAZING IN THE GRASS", "HELLO I LOVE YOU", "PEOPLE GOT TO BE FREE", "HARPER VALLEY PTA", "HEY JUDE", "LOVE CHILD", "I HEARD IT THROUGH THE GRAPEVINE", "CRIMSON AND CLOVER", "EVERYDAY PEOPLE", "DIZZY", "AQUARIUS", "GET BACK", "HONKY TONK WOMEN", "SUGAR SUGAR", "I CANT GET NEXT TO YOU", "SUSPICIOUS MINDS", "COME TOGETHER", "LEAVING ON A JET PLANE", "SOMEDAY WELL BE TOGETHER"]
    },  
  { 
    cat: "Presidents",
    sel: false,
    parent: "",
    numOfItems: 0,
    items: ["GEORGE WASHINGTON", "JOHN ADAMS", "THOMAS JEFFERSON", "JAMES MADISON", "JAMES MONROE", "JOHN QUINCY ADAMS", "ANDREW JACKSON", "MARTIN VAN BUREN", "WILLIAM HENRY HARRISON", "JOHN TYLER", "JAMES K POLK", 
    "ZACHARY TAYLOR", "MILLARD FILLMORE", "FRANKLIN PIERCE", "JAMES BUCHANAN", "ABRAHAM LINCOLN", "ANDREW JOHNSON", "ULYSSES S GRANT", "RUTHERFORD B HAYES", "JAMES GARFIELD", "CHESTER A ARTHUR", "GROVER CLEVELAND", "BENJAMIN HARRISON", "WILLIAM MCKINLEY", "THEODORE ROOSEVELT", "WILLIAM HOWARD TAFT", "WOODROW WILSON", "WARREN G HARDING", "CALVIN COOLIDGE", "HERBERT HOOVER", "FRANKLIN D ROOSEVELT", "HARRY TRUMAN", "DWIGHT EISENHOWER", "JOHN F KENNEDY", "LYNDON JOHNSON", "RICHARD NIXON", "GERALD FORD", "JIMMY CARTER", "RONALD REAGAN", "GEORGE H W BUSH", "BILL CLINTON", "GEORGE W BUSH", "BARACK OBAMA", "DONALD TRUMP", "JOE BIDEN"]
  },  
  { 
    cat: "Words",
    sel: false,
    parent: "",
    numOfItems: 0,
    items: ["ABRUBPTLY", "ABSURD", "ABYSS", "AFFIX", "ASKEW", "AVENUE", "AWKWARD", "AXIOM", "AZURE", "BAGPIPES", "BANDWAGON", "BANJO", "BAYOU", "BEEKEEPER", "BIKINI", "BLITZ", "BLIZZARD"]
  },  
  { 
    cat: "Shakespeare",
    sel: false,
    parent: "",
    numOfItems: 0,
    items: ["TO BE OR NOT TO BE", "FRIENDS ROMANS COUNTRYMEN", "I COME TO BURY CAESAR", "THE BRAVE TASTE OF DEATH BUT ONCE", "BUT CAESAR WAS AMBITIOUS", "AND BRUTUS IS AN HONORABLE MAN", "BUT IN OUR SELVES", "THIS DAY I BREATHED FIRST", "WHERE I DID BEGIN THERE SHALL I END"],
    play: ["Hamlet", "Julius Caesar", "Julius Caesar", "Julius Caesar", "Julius Caesar", "Julius Caesar", "Julius Caesar", "Julius Caesar", "Julius Caesar"],
    character: ["Hamlet", "Marc Antony", "Marc Antony", "Julius Caesar", "Marc Antony", "Marc Antony", "???????", "Gielgud", "Gielgud"],    
    full: ["<strong>To be or not to be</strong>, that is the question. Whether tis", "<strong>Friends Romans Countrymen</strong>, I come to bury Caesar not to praise him", "Friends Romans Countrymen, <strong>I come to bury Caesar</strong> not to praise him", "Cowards die many times <strong>the brave taste of death but once</strong>", "Friends Romans Countrymen, I come to bury Caesar not to praise him", "Friends Romans Countrymen, I come to bury Caesar not to praise him", "The fault lies not in our stars <strong>but in our selves</strong>", "<strong>This day I breathed first</strong>. Time has come round and where I did begin, there shall I end", "This day I breathed first. Time has come round and <strong>where I did begin, there shall I end</strong>"]
  }
]



   
const headerTextEl = document.getElementsByTagName("h1");
const btn = document.getElementById("test")
const scaffoldEl = document.querySelector(".scaffold");

let rCat = 0;
let rItem = 0;

let modal = ""
let span = ""
let answerEl = ""


if (headerTextEl){
  console.log("we have header text " + btn)
}

const hangmanTextEl = document.getElementById("hangman-text");

if (hangmanTextEl){
console.log("hangman text = " + hangmanTextEl.innerText)
}


let r = 0;
let picNum = 0;


let lineWork = [];


/*
btnReplace.addEventListener("click", () => {
  let regex = /[a-zA-Z0-9]/g;
  let result = myString.replace(regex, "#");
  output.innerText = result;
});
*/

initHangman();


function initHangman(){
  let category = JSON.parse(window.localStorage.getItem('hangmanCat'));
  if (category === 9 || !category){
    rCat = Math.floor(Math.random()*cats.length)
  } else {
    rCat = category 
  }

  rItem = Math.floor(Math.random()*cats[rCat].items.length)
  testLine = cats[rCat].items[rItem];
  console.log("hangman solution is " + testLine)
  let regex = /[a-zA-Z]/g;
  testLine = testLine.replace(regex, "-");
  lineWork = testLine.split('');
  hangmanTextEl.innerText = testLine;

  const allAlready = document.querySelectorAll('.already-clicked');

  allAlready.forEach((element) => {
    element.classList.remove('already-clicked');
  });
  picNum = 0;
  scaffoldEl.style.backgroundImage = "";

  $(document).ready(function() {
    $(".cs-text").lettering('words').children('span').lettering()
  });

  
$(document).ready(function() {
  $(".alpha").lettering('words').children('span').lettering()


  initAnswersModal()
});



}


btn.addEventListener("click", function () {
  console.log("clicked on header")

  let category = JSON.parse(window.localStorage.getItem('hangmanCat'));
  if (category === 9 || !category){
    rCat = Math.floor(Math.random()*cats.length)
  } else {
    rCat = category 
  }


console.log("rcat ritem = " + rCat + " " + rItem)

rItem = Math.floor(Math.random()*cats[rCat].items.length)

  testLine = cats[rCat].items[rItem];
  console.log("hangman solution is " + testLine)
  let regex = /[a-zA-Z]/g;
  testLine = testLine.replace(regex, "-");
  lineWork = testLine.split('');
  console.log("lineWork in event listener = " + lineWork)
  hangmanTextEl.innerText = testLine;



  const allAlready = document.querySelectorAll('.already-clicked');

  allAlready.forEach((element) => {
    element.classList.remove('already-clicked');
  });
  picNum = 0;
  scaffoldEl.style.backgroundImage = "";





   
  $(document).ready(function() {
    $(".cs-text").lettering('words').children('span').lettering()
  });
});



addKeyboardClicks();


function addKeyboardClicks(){    
  keyboardClicks = true;
  const keys = document.querySelectorAll(".alpha");
  for (let i = 0; i < keys.length; i++) {
    console.log("keys length = " + keys.length + "i = " + i)
    keys[i].addEventListener("click", ({ target }) => {
      console.log("target = " + target)
      let key = target.innerText;
      console.log ("key = " + key)
      target.blur() 

// If already clicked, no need to check again - just return
      if (target.classList.contains("already-clicked")){
        return;
      };

      found = findAllLetters(key);
      target.classList.add("already-clicked")

      if (found){
        const audio = new Audio ("./auds/shortgood.mp3");
        audio.play(); 
        } else {
        const audio = new Audio ("./auds/pop39222.mp3");
        audio.play();   
        picNum++;
        let pic = `url(./imgs/hang${picNum}.png)`
        scaffoldEl.style.backgroundImage = pic;
        if (picNum === 8){  
        console.log("You lose")  
        const audio = new Audio ("./auds/pop39222.mp3");
        audio.play(); 
        answerEl.innerHTML =  `${cats[rCat].items[rItem]}`
        if (cats[rCat].cat === "Shakespeare"){
          answerEl.innerHTML =  `${cats[rCat].items[rItem]} From the play ${cats[rCat].play[rItem]} spoken by ${cats[rCat].character[rItem]} "${cats[rCat].full[rItem]}"`
        }
        modal.style.display = "block";
      }
        
      }
    

      let text = lineWork.join("")
      hangmanTextEl.innerText = text;

      if (text === cats[rCat].items[rItem]){
        console.log("we have a winner")
        const audio = new Audio ("./auds/shortgood.mp3");
        audio.play(); 
        answerEl.innerHTML = text;  
        if (cats[rCat].cat === "Shakespeare"){
          answerEl.innerHTML = `From the play ${cats[rCat].play[rItem]} spoken by ${cats[rCat].character[rItem]} "${cats[rCat].full[rItem]}"`
        }
        modal.style.display = "block";
      }


      console.log("text after finding letters = " + hangmanTextEl.innerText)
   $(document).ready(function() {
    $(".cs-text").lettering('words').children('span').lettering()
  });

/*
      if (key === "enter") {
        const audio = new Audio ("./auds/hard-keypress.wav");
        audio.play()
        handleSubmitWord();
        return;
      }

      if (key === "del") {
        const audio = new Audio ("./auds/hard-keypress.wav");
        audio.play()
        handleDelete();
        return;
      }

      if (key === "space") {
        const audio = new Audio ("./auds/keypress2.wav");
        audio.play()
        key = " "
      }*/
      const audio = new Audio ("./auds/keypress2.wav");
      audio.play()
 //     updateGuessedLetters(key);
    });
  }  // END OF FOR KEYBOARD LOOP




} // END OF Ians addKeyboardClicks 


function findAllLetters(key){
  console.log("loop thru line in original array and when a match with key is found, put the key into the appropriate index of testLine, then redisplay ")
  let found = false;
  for (i=0; i<cats[rCat].items[rItem].length; i++){
    if (key === cats[rCat].items[rItem][i].toUpperCase()){
       lineWork[i] = cats[rCat].items[rItem][i]
       found = true;
    }
  }
  return found;
}


function initAnswersModal() {
  modal = document.getElementById("answer-modal");
  span = document.getElementById("close-answer");

  answerEl = document.getElementById("view-answer")
  
  
 
  // When the user clicks on <span> (x), close the modal
  span.addEventListener("click", function () {
  modal.classList.toggle("fade-out")
  setTimeout(function(){
    modal.style.display = "none";
    modal.classList.toggle("fade-out")
   }, 2500);

  });
}