let cats = [
  { 
    cat: "Actors",
    sel: false,
    parent: "",
    numOfItems: 0,
    items: ["EMIL JANNINGS", "WARNER BAXTER", "GEORGE ARLISS", "LIONEL BARRYMORE", "WALLACE BEERY", "FREDERIC MARCH", "CHARLES LAUGHTON", "CLARK GABLE", "VICTOR MCLAGLEN", "PAUL MUNI", "SPENCER TRACY", "ROBERT DONAT", "JAMES STEWART", "GARY COOPER", "JAMES CAGNEY", "PAUL LUKAS", "BING CROSBY", "RAY MILLAND", "RONALD COLEMAN", "LAURENCE OLIVIER", "BRODERICK CRAWFORD", "JOSE FERRER", "HUMPHREY BOGART", "GARY COOPER", "WILLIAM HOLDEN", "MARLON BRANDO", "ERNEST BORGNINE", "YUL BRYNNER", "ALEC GUINNESS", "DAVID NIVEN", "CHARLTON HESTON", "BURT LANCASTER", "MAXIMILLIAN SCHELL", "GREGORY PECK", "SIDNEY POITIER", "REX HARRISON", "LEE MARVIN", "PAUL SCOFIELD", "ROD STEIGER", "CLIFF ROBERTSON", "JOHN WAYNE", "GEORGE C SCOTT", "GENE HACKMAN", "JACK LEMMON", "ART CARNEY", "JACK NICHOLSON", "PETER FINCH", "RICHARD DREYFUSS", "JON VOIGHT", "DUSTIN HOFFMAN", "ROBERT DE NERO", "HENRY FONDA", "BEN KINGSLEY", "ROBERT DUVALL", "F MURRAY ABRAHAM", "WILLIAM HURT", "PAUL NEWMAN", "MICHAEL DOUGLAS", "DANIEL DAY LEWIS", "JEREMY IRONS", "ANTHONY HOPKINS", "AL PACINO", "TOM HANKS", "NICOLAS CAGE", "GEOFFREY RUSH", "ROBERTO BENIGNI", "KEVIN SPACEY", "RUSSELL CROWE", "DENZEL WASHINGTON", "ADRIEN BRODY", "SEAN PENN", "JAMIE FOXX", "PHILIP SEYMOUR HOFFMAN", "FOREST WHITAKER", "JEFF BRIDGES", "COLIN FIRTH", "JEAN DUJARDIN", "MATTHEW MCCONAUGHEY", "EDDIE REDMAYNE", "LEONARDO DICAPRIO", "CASEY AFFLECK", "GARY OLDMAN", "RAMI MALEK", "JOAQUIN PHOENIX", "ANTHONY HOPKINS", "WILL SMITH", "FRANCHOT TONE", "THOMAS MITCHELL", "CLAUDE RAINS", "PAUL HENRIED", "ERROL FLYNN", "CARY GRANT", "LEO G CARROLL", "JAMES MASON", "LOUIS HAYWARD", "HENRY DANIELL", "ROBERT TAYLOR", "WALTER HUSTON", "JOHN HUSTON", "RANDOLPH SCOTT", "WALTER BRENNAN", "WILLIAM POWELL", "VAN JOHNSON", "CHARLIE CHAPLIN", "LESLIE HOWARD", "RALPH BELLAMY", "RAYMOND MASSEY", "C AUBREY SMITH", "DOUGLAS FAIRBANKS JR", "FRED ASTAIRE", "BASIL RATHBONE", "TYRONE POWER", "DON AMECHE", "MICHAEL REDGRAVE", "BRIAN DONLEVY", "RALPH RICHARDSON", "EDWARD ARNOLD", "MELVYN DOUGLAS", "BELA LUGOSI", "BORIS KARLOFF", "CECIL KELLAWAY", "WARD BOND", "JOEL MCCREA", "ROBERT YOUNG", "VAN HEFLIN", "FRANK MORGAN", "CONRAD VEIDT", "WALTER PIDGEON", "RODDY MCDOWALL", "DONALD CRISP", "PETER LORRE", "SYDNEY GREENSTREET", "WARD BOND", "ELISHA COOK JR", "ROBERT MORLY", "REX HARRISON", "EDWARD G ROBINSON", "CEDRIC HARDWICKE", "NIGEL BRUCE", "KENT SMITH", "TOM CONWAY", "GEORGE SANDERS", "JOSEPH COTTEN", "ROBERT CUMMINGS", "OTTO KRUGER", "ALAN LADD", "JACK BENNY", "FRED MACMURRAY", "CHARLES BOYER", "BARRY FITZGERALD", "DANA ANDREWS", "CLIFTON WEBB", "VINCENT PRICE", "JOHN HODIAK", "WALTER SLEZAK", "WILLIAM BENDIX", "DICK POWELL", "MIKE MAZURKI", "MICKEY ROONEY", "GENE KELLY", "FRANK SINATRA", "CORNEL WILDE", "EDMOND OBRIEN", "JACK PALANCE", "ZERO MOSTEL", "RICHARD WIDMARK", "TOSHIRO MIFUNE", "ALASTAIR SIM", "MONTGOMERY CLIFT", "TREVOR HOWARD", "ROBERT RYAN", "EDMUND GWENN", "ROBERT MITCHUM", "DANNY KAYE", "GLENN FORD", "JOHN GARFIELD", "JAMES DEAN", "CLIFF ROBERTSON", "GORDON MACRAE", "PETER SELLERS", "VAN JOHNSON", "JOSE FERRER", "BROCK PETERS", "RICHARD CARLSON", "HUGH MARLOWE", "RAYMOND BURR", "LEE J COBB", "WENDELL COREY", "JOHN WILLIAMS", "MICHAEL RENNIE", "OSKAR WERNER", "FARLEY GRANGER", "JOHN GIELGUD", "TONY CURTIS", "ANTHONY PERKINS", "ELI WALLACH", "STEVE MCQUEEN", "CHARLES BRONSON", "JAMES COBURN", "ROBERT VAUGHN", "STEPHEN BOYD", "JACK HAWKINS", "HUGH GRIFFITH", "E G MARSHALL", "DEAN MARTIN", "PAUL NEWMAN", "SESSUE HAYAKAWA", "ANDY GRIFFITH", "ROBERT REDFORD", "DENNIS HOPPER", "NIGEL TERRY", "TIMOTHY DALTON", "GENE WILDER", "MICHAEL YORK", "JOHN CASSAVETES", "GEORGE KENNEDY", "STROTHER MARTIN", "PETER FINCH", "MICHAEL CAINE", "ROBERT SHAW", "LEO MCKERN", "JOHN HURT", "OMAR SHARIFF", "CHRISOPHER PLUMMER", "JAMES GARNER", "ANTHONY QUINN", "ROD TAYLOR", "ANGUS LENNIE", "DAVID MCCALLUM", "ALBERT FINNEY", "TERENCE STAMP", "PETER USTINOV", "LAURENCE HARVEY", "JAMES GREGORY","GEORGE PEPPARD", "RICHARD WIDMARK", "RICHARD GERE", "DENHOLM ELLIOTT", "SEAN CONNERY", "ROGER MOORE", "GEORGE LAZENBY", "CHIEF DAN GEORGE", "BURGESS MEREDITH", "ROY SCHEIDER", "SAEED JAFFREY", "ARNOLD SCHWARZENEGGER", "JOHNNY DEPP", "KEVIN COSTNER", "ED HARRIS", "MARTIN LANDAU", "KENNETH BRANAGH", "BILLY CRYSTAL"]
    },
  { 
    cat: "Actresses",
    sel: false,
    parent: "",
    numOfItems: 0,
    items: ["JANET GAYNOR", "MARY PICKFORD", "NORMA SHEARER", "MARIE DRESSLER", "HELEN HAYES", "KATHARINE HEPBURN", "CLAUDETTE COLBERT", "BETTE DAVIS", "LUISE RAINER", "VIVIEN LEIGH", "GINGER ROGERS", "JOAN FONTAINE", "GREER GARSON", "JENNIFER JONES", "INGRID BERGMAN", "JOAN CRAWFORD", "OLIVIA DE HAVILLAND", "LORETTA YOUNG", "JANE WYMAN", "JUDY HOLLIDAY", "SHIRLEY BOOTH", "AUDREY HEPBURN", "GRACE KELLY", "ANNA MAGNANI", "JOANNE WOODWARD", "SUSAN HAYWARD", "SIMONE SIGNORET", "ELIZABETH TAYLOR", "SOPHIA LOREN", "ANNE BANCROFT", "PATRICIA NEAL", "JULIE ANDREWS", "JULIE CHRISTIE", "BARBRA STREISAND", "MAGGIE SMITH", "GLENDA JACKSON", "JANE FONDA", "LIZA MINNELLI", "ELLEN BURSTYN", "LOUISE FLETCHER", "FAYE DUNAWAY", "DIANE KEATON", "SALLY FIELD", "SISSY SPACEK", "MERYL STREEP", "SHIRLEY MACLAINE", "GERALDINE PAGE", "MARLEE MATLIN", "CHER", "JODIE FOSTER", "JESSICA TANDY", "KATHY BATES", "EMMA THOMPSON", "HOLLY HUNTER", "JESSICA LANGE", "SUSAN SARANDON", "FRANCES MCDORMAND", "HELEN HUNT", "GWYNETH PALTROW", "HILARY SWANK", "JULIA ROBERTS", "HALLE BERRY", "NICOLE KIDMAN", "CHARLIZE THERON", "REESE WITHERSPOON", "HELEN MIRREN", "MARION COTILLARD", "KATE WINSLET", "SANDRA BULLOCK", "NATALIE PORTMAN", "JENNIFER LAWRENCE", "CATE BLANCHETT", "JULIANNE MOORE", "BRIE LARSON", "EMMA STONE", "OLIVIA COLMAN", "RENEE ZELLWEGER", "JESSICA CHASTAIN", "BARBARA BAIN", "GALE SONDERGAARD", "GRETA GARBO", "MARY ASTOR", "MADELEINE CARROLL", "MYRNA LOY", "ESTHER WILLIAMS", "LUCILLE BALL", "JEAN ARTHUR", "IRENE DUNNE", "BARBARA STANWYCK", "CONSTANCE BENNETT", "DAME MAY WHITTY", "MARGARET LOCKWOOD", "WENDY HILLER", "MARLENE DIETRICH", "EDNA MAY OLIVER", "HATTIE MCDANIEL", "MAUREEN OHARA", "CLAIRE TREVOR", "JUDY GARLAND", "MERLE OBERON", "FLORA ROBSON", "LARAINE DAY", "LINDA DARNELL", "MARGARET SULLAVAN", "JUDITH ANDERSON", "JUNE DUPREZ", "IDA LUPINO", "TERESA WRIGHT", "VERONICA LAKE", "CAROLE LOMBARD", "ELSA LANCHESTER", "AGNES MOOREHEAD", "GERALDIN FITZGERALD", "PRISCILLA LANE", "GENE TIERNEY", "TALLULAH BANKHEAD", "LAUREN BACALL", "ANNE BAXTER", "GLORIA SWANSON", "JOAN BENNETT", "SHIRLEY TEMPLE", "VIRGINIA MAYO", "JEAN SIMMONS", "RITA HAYWORTH", "DEBORAH KERR", "SIGNE HASSO", "NATALIE WOOD", "LANA TURNER", "MARILYN MONROE", "SUSAN HAYWARD", "ANGELA LANSBURY", "KIM HUNTER", "DEBBIE REYNOLDS", "GLORIA GRAHAME", "AVA GARDNER", "JANET LEIGH", "VERA MILES", "LEE REMICK", "HAYA HARAREET", "ANGIE DICKENSON", "ROSALIND RUSSELL", "JEAN SIMMONS", "KIM NOVAK", "AUDREY HEPBURN", "KATHARINE ROSS", "CLAUDIA CARDINALE", "PATTY DUKE", "VANESSA REDGRAVE", "HONOR BLACKMAN", "TIPPI HEDREN", "MARY BADHAM", "COLLIN WILCOX", "SIGOURNEY WEAVER", "SHARON STONE", "CLAIRE BLOOM", "MEG RYAN", "RAQUEL WELCH"]
    },
    { 
      cat: "Countries",
      sel: false,
      parent: "",
      numOfItems: 0,
      items: ["AFGHANISTAN", "ALBANIA", "ALGERIA", "ANDORRA", "ANGOLA", "ARGENTINA", "ARMENIA", "AUSTRALIA", "AUSTRIA", "AZERBAIJAN", "BAHAMAS", "BAHRAIN", "BANGLADESH", "BARBADOS", "BELARUS", "BELGIUM", "BELIZE", "BENIN", "BHUTAN", "BOLIVIA", "BOSNIA AND HERZEGOVINA", "BOTSWANA", "BRAZIL", "BRUNEI", "BULGARIA", "BURKINA FASO", "BURUNDI", "CAMBODIA", "CAMEROON", "CANADA", "CENTRAL AFRICAN REPUBLIC", "CHAD", "CHILE", "CHINA", "COLUMBIA", "CONGO REPUBLIC OF THE", "COSTA RICA", "COTE DIVOIRE", "CROATIA", "CUBA", "CYPRUS", "CZECH REPUBLIC", "DENMARK", "DJIBOUTI", "DOMINICA", "DOMINICAN REPUBLIC", "ECUADOR", "EGYPT", "EL SALVADOR", "EQUATORIAL GUINEA", "ERITREA", "ESTONIA", "ETHIOPIA", "FIJI", "FINLAND", "FRANCE", "GABON", "GAMBIA", "GEORGIA", "GERMANY", "GHANA", "GREECE", "GRENADA", "GUATEMALA", "GUYANA", "HAITI", "HONDURAS", "HUNGARY", "ICELAND", "INDONESIA", "INDIA", "IRAN", "IRAQ", "IRELAND", "ISRAEL", "ITALY", "JAMAICA", "JAPAN", "JORDAN","KAZAKHSTAN", "KENYA", "KOSOVO", "KUWAIT", "KYRGYZSTAN", "LAOS", "LATVIA", "LEBANON", "LESOTHO", "LIBERIA", "LIBYA", "LIECHTENSTEIN", "LITHUANIA", "LUXEMBOURG", "MADAGASCAR", "MALAWI", "MALAYSIA", "MALDIVES", "MALI", "MALTA", "MARSHALL ISLANDS", "MAURITANIA", "MAURITIUS", "MEXICO", "MICRONESIA", "MOLDOVA", "MONACO", "MONTENEGRO", "MOROCCO", "MOZAMBIQUE", "MYANMAR", "NAMIBIA", "NEPAL", "NETHERLANDS", "NEW ZEALAND", "NICARAGUA", "NIGER", "NIGERIA", "NORTH KOREA", "NORTH MACEDONIA", "NORWAY", "OMAN", "PAKISTAN", "PALESTINE","PANAMA", "PAPUA NEW GUINEA", "PARAGUAY", "PERU", "PHILIPPINES", "POLAND", "PORTUGAL", "QATAR", "ROMANIA", "RUSSIA", "RWANDA", "SAINT KITTS AND NEVIS", "SAINT LUCIA", "SAINT VINCENT AND THE GRENADINES", "SAMOA", "SAN MARINO", "SAUDI ARABIA", "SENEGAL", "SERBIA", "SEYCHELLES", "SIERRA LEONE", "SINGAPORE", "SLOVAKIA", "SLOVENIA", "SOLOMON ISLANDS", "SOMALIA", "SOUTH AFRICA", "SOUTH KOREA", "SOUTH SUDAN", "SPAIN", "SRI LANKA", "SUDAN", "SURINAME", "SWEDEN", "SWITZERLAND", "SYRIA", "TAIWAN", "TAJIKISTAN", "TANZANIA", "THAILAND", "TOGO", "TONGA", "TRINIDAD AND TOBAGO", "TUNISIA", "TURKEY", "TURKMENISTAN", "TUVALU", "UGANDA","UKRAINE", "UNITED ARAB EMIRATES", "UNITED KINGDOM", "UNITED STATES OF AMERICA", "URUGUAY", "UZBEKISTAN", "VATICAN CITY", "VENEZUELA", "VIETNAM", "YEMEN", "ZAMBIA", "ZIMBABWE"] 
    }, 
    { 
    cat: "Geo Features",
    sel: false,
    parent: "",
    numOfItems: 0,
    items: ["THE AMAZON", "THE NILE", "THE HUDSON", "THE SAHARA", "MT EVEREST", "THE GREAT SALT LAKE", "HIGH POINT", "THE ATLANTIC OCEAN", "THE PACIFIC OCEAN", "THE INDIAN OCEAN", "NORTH AMERICA", "EUROPE", "ASIA", "SOUTH AMERICA", "AFRICA", "MT WASHINGTON", "THE GOBI DESERT", "PIKES PEAK", "CRATER LAKE", "MT SAINT HELENS", "MT FUJI", "MT KILIMANJARO", "MT KENYA", "ACONGAGUA", "AMAZON RAIN FOREST", "DENALI", "MONT BLANC", "THE MATTERHORN", "THE JUNGFRAU", "THE EIGER", "THE THAMES", "THE SEINE", "THE DANUBE", "THE DNEIPER", "THE VOLGA","THE RIO GRANDE", "THE MISSISSIPPI", "THE MISSOURI", "ANTARCTICA", "THE GREAT BARRIER REEF", "NIAGARA FALLS", "ANGEL FALLS", "EL CAPITAN", "HALF DOME", "DEVILS TOWER", "MT RUSHMORE", "CATSKILLS", "ADIRONDACKS", "ROCKIES", "HIMALAYAS", "ANDES", "ALPS", "CARPATHIANS", "ATLAS", "AYERS ROCK", "EVERGLADES", "GREAT SMOKEY MOUNTAINS"]
    },  
    { 
    cat: "Movies",
    sel: false,
    parent: "",
    numOfItems: 0,
    items: ["WINGS", "THE BROADWAY MELODY", "CIMMARON", "GRAND HOTEL",  "CAVALCADE", "IT HAPPENED ONE NIGHT", "MUTINY ON THE BOUNTY", "THE GREAT ZIEGFELD", "THE LIFE OF EMILE ZOLA", "GONE WITH THE WIND", "REBECCA", "HOW GREEN WAS VALLEY", "MRS MINIVER", "CASABLANCA", "GOING MY WAY", "THE LOST WEEKEND", "GENTLEMANS AGREEMENT", "HAMLET", "ALL THE KINGS MEN", "ALL ABOUT EVE", "AN AMERICAN IN PARIS", "THE GREATEST SHOW ON EARTH", "FROM HERE TO ETERNITY", "ON THE WATERFRONT", "MARTY", "THE BRIDGE ON THE RIVER KWAI", "GIGI", "BEN HUR", "THE APARTMENT", "WEST SIDE STORY", "LAWRENCE OF ARABIA", "TOM JONES", "MY FAIR LADY", "THE SOUND OF MUSIC", "A MAN FOR ALL SEASONS", "IN THE HEAT OF THE NIGHT", "OLIVER", "MIDNIGHT COWBOY", "PATTON", "THE FRENCH CONNECTION", "THE GODFATHER", "THE STING", "THE GODFATHER PART II", "ROCKY", "ANNIE HALL", "THE DEER HUNTER", "KRAMER VS KRAMER", "ORDINARY PEOPLE", "CHARIOTS OF FIRE", "GANDHI", "TERMS OF ENDEARMENT", "AMADEUS", "OUT OF AFRICA", "PLATOON", "THE LAST EMPEROR", "RAIN MAN", "DRIVING MISS DAISY", "DANCES WITH WOLVES", "THE SILENCE OF THE LAMBS", "UNFORGIVEN", "SCHINDLERS LIST", "FORREST GUMP", "BRAVEHEART", "THE ENGLISH PATIENT", "TITANIC", "SHAKESPEARE IN LOVE", "AMERICAN BEAUTY", "GLADIATOR", "A BEAUTIFUL MIND", "CHICAGO", "LORD OF THE RINGS", "MILLION DOLLAR BABY", "CRASH", "THE DEPARTED", "NO COUNTRY FOR OLD MEN", "SLUMDOG MILLIONAIRE", "THE HURT LOCKER", "THE KINGS SPEECH", "THE ARTIST", "ARGO", "TWELVE YEARS A SLAVE", "BIRDMAN", "SPOTLIGHT", "MOONLIGHT", "THE SHAPE OF WATER", "GREEN BOOK", "PARASITE", "NOMADLAND", "CODA", "MODERN TIMES", "THE PETRIFIED FOREST", "THE GOOD EARTH", "LOST HORIZON", "THE PRISONER OF ZENDA", "TOPPER", "THE ADVENTURES OF ROBIN HOOD", "BRINGING UP BABY", "THE LADY VANISHES", "YOU CANT TAKE IT WITH YOU", "DESTRY RIDES AGAIN", "THE FOUR FEATHERS", "GOODBYE MR CHIPS", "GUNGA DIN", "THE HUNCHBACK OF NOTRE DAME", "MR SMITH GOES TO WASHINGTON", "NINOTCHKA", "STAGECOACH", "THE WIZARD OF OZ", "WUTHERING HEIGHTS", "ABE LINCOLN IN ILLINOIS", "FANTASIA", "FOREIGN CORRESPONDENT", "THE GRAPES OF WRATH", "THE GREAT DICTATOR", "HIS GIRL FRIDAY", "THE MARK OF ZORRO", "THE PHILADELPHIA STORY", "PRIDE AND PREJUDICE", "REBECCA", "THE SEA HAWK", "THE SHOP AROUND THE CORNER", "THE THIEF OF BAGDAD", "CITIZEN KANE", "HERE COMES MR JORDAN", "HIGH SIERRA", "HOW GREEN WAS MY VALLEY", "THE MALTESE FALCON", "MEET JOHN DOE", "THE SEA WOLF", "SERGEANT YORK", "SUSPICION", "THAT HAMILTON WOMAN", "THE WOLF MAN", "CASABLANCA", "KINGS ROW", "THE MAGNIFICENT AMBERSONS", "NOW VOYAGER", "THE PRIDE OF THE YANKEES", "RANDOM HARVEST", "SABOTEUR", "TO BE OR NOT TO BE", "FOR WHOM THE BELL TOLLS", "HEAVEN CAN WAIT", "JANE EYRE", "THE OX BOW INCIDENT", "PHANTOM OF THE OPERA", "SHADOW OF A DOUBT", "THE SONG OF BERNADETTE", "WATCH ON THE RHINE", "ARSENIC AND OLD LACE", "DOUBLE INDEMNITY", "GASLIGHT", "GOING MY WAY", "HENRY V", "LAURA", "LIFEBOAT", "MEET ME IN ST LOUIS", "MURDER MY SWEET", "NATIONAL VELVET", "TO HAVE AND HAVE NOT", "AND THEN THERE WERE NONE", "THE BELLS OF ST MARYS", "THE BODY SNATCHER", "LEAVE HER TO HEAVEN", "MILDRED PIERCE", "THE PICTURE OF DORIAN GRAY", "SPELLBOUND", "A TREE GROWS IN BROOKLYN", "THE BEST YEARS OF OUR LIVES", "THE BIG SLEEP", "ITS A WONDERFUL LIFE", "MY DARLING CLEMENTINE", "NOTORIOUS", "THE POSTMAN ALWAYS RINGS TWICE", "THE SPIRAL STAIRCASE", "THE STRANGER", "THE YEARLING", "THE BACHELOR AND THE BOBBY SOXER", "THE BISHOPS WIFE", "BLACK NARCISSUS", "CROSSFIRE", "DARK PASSAGE", "A DOUBLE LIFE", "THE FARMERS DAUGHTER", "GENTLEMANS AGREEMENT", "THE GHOST AND MRS MUIR", "THE SECRET LIFE OF WALTER MITTY", "I REMEMBER MAMA", "JOHNNY BELINDA", "KEY LARGO", "THE LADY FROM SHANGHAI", "RED RIVER", "THE RED SHOES", "ROPE", "THE SNAKE PIT", "THE TREASURE OF THE SIERRA MADRE", "ALL THE KINGS MEN", "THE FOUNTAINHEAD", "THE HEIRESS", "KIND HEARTS AND CORONETS", "ON THE TOWN", "SHE WORE A YELLOW RIBBON", "THE THIRD MAN", "TWELVE OCLOCK HIGH", "WHITE HEAT", "ALL ABOUT EVE", "THE ASPHALT JUNGLE", "BORN YESTERDAY", "FATHER OF THE BRIDE", "HARVEY", "RASHOMON", "SUNSET BOULEVARD", "THE AFRICAN QUEEN", "AN AMERICAN IN PARIS", "A CHRISTMAS CAROL", "THE DAY THE EARTH STOOD STILL", "A PLACE IN THE SUN", "QUO VADIS", "STRANGERS ON A TRAIN", "A STREETCAR NAMED DESIRE", "THE THING", "THE GREATEST SHOW ON EARTH", "HIGH NOON", "THE QUIET MAN", "SINGIN IN THE RAIN", "I CONFESS", "JULIUS CAESAR", "NIAGARA", "THE ROBE", "ROMAN HOLIDAY", "SHANE", "THE WAR OF THE WORLDS", "THE CAINE MUTINY", "CREATURE FROM THE BLACK LAGOON", "DIAM M FOR MURDER", "THE FAR COUNTRY", "GODZILLA", "REAR WINDOW", "SABRINA", "A STAR IS BORN", "BAD DAY AT BLACK ROCK", "BLACKBOARD JUNGLE", "THE COURT JESTER", "EAST OF EDEN", "GUYS AND DOLLS", "THE LADYKILLERS", "MISTER ROBERTS", "OKLAHOMA", "PICNIC", "REBEL WITHOUT A CAUSE", "RICHARD III", "TO CATCH A THIEF", "ANASTASIA", "FRIENDLY PERSUASION", "GIANT", "HIGH SOCIETY", "INVASION OF THE BODY SNATCHERS", "THE KING AND I", "THE MAN WHO KNEW TOO MUCH", "MOBY DICK", "THE SEARCHERS", "THE TEN COMMANDMENTS", "AN AFFAIR TO REMEMBER", "A FACE IN THE CROWD", "GUNFIGHT AT THE OK CORRAL", "THE INCREDIBLE SHRINKING MAN", "PATHS OF GLORY", "THE THREE FACES OF EVE", "TWELVE ANGRY MEN", "WILD STRAWBERRIES", "WITNESS FOR THE PROSECUTION", "AUNTIE MAME", "THE BIG COUNTRY", "TOUCH OF EVIL", "VERTIGO", "ANATOMY OF A MURDER", "NORTH BY NORTHWEST", "RIO BRAVO", "SOME LIKE IT HOT", "ELMER GANTRY", "INHERIT THE WIND", "THE MAGNIFICENT SEVEN", "PSYCHO", "SPARTACUS", "THE SUNDOWNERS", "BREAKFAST AT TIFFANYS", "THE GUNS OF NAVARONE", "JUDGEMENT AT NUREMBURG", "SPLENDOR IN THE GRASS", "BILLY BUDD", "CAPE FEAR", "DR NO", "HOW THE WEST WAS WON", "LOLITA", "THE LONGEST DAY", "THE MAN WHO SHOT LIBERTY VALANCE", "THE MANCHURIAN CANDIDATE", "THE MIRACLE WORKER", "TO KILL A MOCKINGBIRD", "WHAT EVER HAPPENED TO BABY JANE", "THE BIRDS", "BYE BYE BIRDIE", "CHARADE", "FROM RUSSIA WITH LOVE", "THE HAUNTING", "LILIES OF THE FIELD", "THE NUTTY PROFESSOR", "THE PINK PANTHER", "TOM JONES", "DR STRANGELOVE", "FAIL SAFE", "GOLDFINGER", "A HARD DAYS NIGHT", "MARNIE", "MARY POPPINS", "MY FAIR LADY", "THE NIGHT OF THE IGUANA", "THE PAWNBROKER", "A SHOT IN THE DARK", "ZORBA THE GREEK", "ZULU", "DOCTOR ZHIVAGO", "HELP", "BORN FREE", "FANTASTIC VOYAGE", "BONNIE AND CLYDE", "COOL HAND LUKE", "THE DIRTY DOZEN", "THE GRADUATE", "GUESS WHOS COMING TO DINNER", "IN THE HEAT OF THE NIGHT", "WAIT UNTIL DARK", "BULLIT", "CHARLY", "FUNNY GIRL", "THE LION IN WINTER", "NIGHT OF THE LIVING DEAD", "PLANET OF THE APES", "THE PRODUCERS", "ROSEMARYS BABY", "THE THOMAS CROWN AFFAIR", "BUTCH CASSIDY AND THE SUNDANCE KID", "EASY RIDER", "THE PRIME OF MISS JEAN BRODIE", "TRUE GRIT", "THE WILD BUNCH", "FIVE EASY PIECES", "A CLOCKWORK ORANGE", "DEATH IN VENICE", "DIRTY HARRY", "FIDDLE ON THE ROOF", "HAROLD AND MAUDE", "THE LAST PICTURE SHOW", "NICHOLAS AND ALEXANDRA", "PLAY MISTY FOR ME", "SHAFT", "SUNDAY BLOODY SUNDAY", "CABARET", "DELIVERANCE", "FRENZY", "LAST TANGO IN PARIS", "SLEUTH", "SOUNDER", "SUPER FLY", "AMERICAN GRAFFITI", "THE DAY OF THE JACKAL", "ENTER THE DRAGON", "THE EXORCIST", "HIGH PLAINS DRIFTER", "MEAN STREETS", "THE PAPER CHASE", "PAPER MOON", "PAPILLON", "SERPICO", "SLEEPER", "BLAZING SADDLES", "CHINATOWN", "THE CONVERSATION", "HARRY AND TONTO", "THE TOWERING INFERNO", "YOUNG FRANKENSTEIN", "BARRY LYNDON", "DOG DAY AFTERNOON", "JAWS", "THE MAN WHO WOULD BE KING", "MONTY PYTHON AND THE HOLY GRAIL", "ALL THE PRESIDENTS MEN", "MARATHON MAN", "NETWORK", "THE OMEN", "TAXI DRIVER", "CLOSE ENCOUNTERS OF THE THIRD KIND", "SATURDAY NIGHT FEVER", "THE SPY WHO LOVED ME", "STAR WARS", "COMING HOME", "MIDNIGHT EXPRESS", "WATERSHIP DOWN", "ALIEN", "APOCALYPSE NOW", "BEING THERE", "THE CHINA SYNDROME", "NORMA RAE", "RAGING BULL", "THE SHINING", "ARTHUR", "BODY HEAT", "DAS BOOT", "GALLIPOLI", "THE ROAD WARRIOR", "MY DINNER WITH ANDRE", "RAGTIME", "RAIDERS OF THE LOST ARK", "BLADE RUNNER", "DINER", "E T THE EXTRA TERRESTRIAL", "AN OFFICER AND A GENTLEMAN", "POLTERGEIST", "SOPHIES CHOICE", "TOOTSIE", "THE VERDICT", "THE BIG CHILL", "A CHRISTMAS STORY", "FLASHDANCE", "RETURN OF THE JEDI", "THE RIGHT STUFF", "RISKY BUSINESS", "SUDDEN IMPACT", "TENDER MERCIES", "GHOSTBUSTERS", "THE KILLING FIELDS", "THE NATURAL", "A PASSAGE TO INDIA", "ROMANCING THE STONE", "THE TERMINATOR", "THIS IS SPINAL TAP", "BACK TO THE FUTURE", "THE BREAKFAST CLUB", "THE COLOR PURPLE", "PALE RIDER", "PRIZZIS HONOR", "A ROOM WITH A VIEW", "WITNESS", "ALIENS", "CHILDREN OF A LESSER GOD", "THE COLOR OF MONEY", "CROCODILE DUNDEE", "THE FLY", "HANNAH AND HER SISTERS", "THE MISSION", "PLATOON", "STAND BY ME", "TOP GUN", "DIRTY DANCING", "FATAL ATTRACTION", "FULL METAL JACKET", "GOOD MORNING VIETNAM", "THE LAST EMPEROR", "LETHAL WEAPON", "MOONSTRUCK", "PREDATOR", "THE PRINCESS BRIDE", "SUSPECT", "THE UNTOUCHABLES", "THE ACCIDENTAL TOURIST", "BULL DURHAM", "CINEMA PARDISO", "DANGEROUS LIAISONS", "DIE HARD", "A FISH CALLED WANDA", "MISSISSIPPI BURNING", "WHO FRAMED ROGER RABBIT", "THE ABYSS", "BATMAN", "BORN ON THE FOURTH OF JULY", "DEAD POETS SOCIETY", "DO THE RIGHT THING", "DRIVING MISS DAISY", "FIELD OF DREAMS", "GLORY", "HENRY V", "MY LEFT FOOT", "WHEN HARRY MET SALLY", "AWAKENINGS", "DANCES WITH WOLVES", "EDWARD SCISSORHANDS", "GOODFELLAS", "HOME ALONE", "PRESUMED INNOCENT", "PRETTY WOMAN", "REVERSAL OF FORTUNE", "TOTAL RECALL", "CITY SLICKERS", "FRIED GREEN TOMATOS", "THELMA AND LOUISE", "ALADDIN", "BASIC INSTINCT", "A FEW GOOD MEN", "THE LAST OF THE MOHICANS", "MY COUSIN VINNY", "MALCOLM X", "A RIVER RUNS THROUGH IT", "SCENT OF WOMAN", "THE FUGITIVE", "GROUNDHOG DAY", "IN THE NAME OF THE FATHER", "THE JOY LUCK CLUB", "JURASSIC PARK", "MRS DOUBTFIRE", "PHILADELPHIA", "THE PIANO", "THE REMAINS OF THE DAY", "SLEEPLESS IN SEATTLE", "HOOP DREAMS", "THE LION KING", "THE MADNESS OF KING GEORGE", "PULP FICTION", "THE SHAWSHANK REDEMPTION", "TRIAL BY JURY", "TRUE LIES", "THE BRIDGES OF MADISON COUNTY", "CASINO", "GOLDENEYE", "LEAVING LAS VEGAS", "SENSE AND SENSIBILITY", "TOY STORY", "DR NO", "FROM RUSSIA WITH LOVE", "THUNDERBALL", "DIAMONDS ARE FOREVER", "YOU ONLY LIVE TWICE", "ON HER MAJESTYS SECRET SERVICE", "LIVE AND LET DIE", "THE SPY WHO LOVED ME", "FOR YOUR EYES ONLY", "A VIEW TO A KILL", "THE LIVING DAYLIGHTS", "LICENSE TO KILL", "THE MAN WITH THE GOLDEN GUN", "THE SPY WHO LOVED ME", "MOONRAKER", "OCTOPUSSY", "NEVER SAY NEVER AGAIN", "FARGO", "INDEPENDENCE DAY", "JERRY MAGUIRE", "TWISTER", "AMISTAD", "GOOD WILL HUNTING", "TITANIC", "THE BIG LEBOWSKI", "SAVING PRIVATE RYAN", "THERES SOMETHING ABOUT MARY", "BEING JOHN MALKOVICH", "THE BLAIR WITCH PROJECT", "THE MATRIX", "THE SIXTH SENSE", "CROUCHING TIGER HIDDEN DRAGON", "ERIN BROCKOVICH"]
    },
    { 
      cat: "Movie Characters",
      sel: false,
      parent: "",
      numOfItems: 0,
      items: ["CAPTAIN BLIGH", "FLETCHER CHRISTIAN", "SCARLETT OHARA", "RHETT BUTLER", "RICK BLAINE", "ILSA LUND", "VICTOR LASZLO", "CAPTAIN LOUIS RENAULT", "MAXIM DE WINTER", "MRS DANVERS", "COLONEL NICHOLSON", "COLONEL SAITO", "JOHN ROBIE", "GUY HAINES", "BRUNO ANTONY", "WILLIE STARK", "ROGER THORNHILL", "EVE KENDALL", "PHILLIP VANDAMM", "LESTER TOWNSEND", "JUDAH BEN HUR", "MESSALA", "QUINTUS ARIUS", "BOO RADLEY", "ATTICUS FINCH", "SCOUT FINCH", "JEM FINCH", "TOM ROBINSON", "ROBERT E LEE EWELL", "MAYELLA VIOLET EWELL", "T E LAWRENCE", "MARIA VON TRAPP", "HENRY HIGGINS", "ELIZA DOOLITTLE", "SAM SPADE", "MILES ARCHER", "JOEL CAIRO", "THOMAS MOORE", "HENRY VIII", "RICHARD RICH", "VIRGIL TIBBS", "CHIEF GILLESPIE", "GEORGE S PATTON", "VITO CORLEONE", "ROCKY BALBOA", "RAYMOND BABBIT", "CHARLIE BABBIT", "GEORGE KIRBY", "MARIAN KIRBY", "COSMO TOPPER", "ROBIN HOOD", "LITTLE JOHN", "FRIAR TUCK", "MAID MARIAN", "GUY OF GISBOURNE", "PRINCE JOHN", "DAPHNE", "JOSEPHINE", "SUGAR", "MISS FROI", "TOM DESTRY", "GUNGA DIN", "RUDYARD KIPLING", "QUASIMODO", "ESMERALDA", "JEFFERSON SMITH", "SENATOR JOSEPH PAINE", "DOROTHY GALE", "THE SCARECROW", "THE COWARDLY LION", "THE TIN MAN", "WICKED WITCH OF THE WEST", "ALMIRA GULCH", "HEATHCLIFF", "DON DIEGO DE LA VEGA", "TOM JOAD", "MA JOAD", "CHARLES FOSTER KANE", "DUKE MANTEE", "MORTIMER BREWSTER", "WALTER NEFF", "PHYLLIS DIETRICHSON", "LAURA HUNT", "WALDO LYDECKER", "MARK MCPHERSON", "SHELBY CARPENTER", "PHILIP MARLOWE", "DORIAN GRAY", "BIG X", "COOLER KING", "TUNNEL KING", "THE FORGER", "ERIC ASHLEY PITT", "ARCHIBALD IVES", "THE SCROUNGER", "FATHER OMALLY", "ROGER BARTLETT", "VIRGIL HILTS"]
    },
    {
      cat: "Beatles Songs",
      sel: false,
      parent: "Music",
      numOfItems: 0,
      items: ["I SAW HER STANDING THERE", "MISERY", "LOVE ME DO", "PS I LOVE YOU", "DO YOU WANT TO KNOW A SECRET", "A TASTE OF HONEY", "TWIST AND SHOUT", "I WANT TO HOLD YOUR HAND", "THIS BOY", "IT WONT BE LONG", "ALL IVE GOT TO DO", "ALL MY LOVING", "DONT BOTHER ME", "LITTLE CHILD", "TIL THERE WAS YOU", "HOLD ME TIGHT", "I WANNA BE YOUR MAN", "NOT A SECOND TIME", "THANK YOU GIRL", "YOU REALLY GOT A HOLD ON ME", "MONEY", "YOU CANT DO THAT", "LONG TALL SALLY", "I CALL YOUR NAME", "PLEASE MR POSTMAN", "ILL GET YOU", "SHE LOVES YOU", "A HARD DAYS NIGHT", "TELL ME WHY", "ILL CRY INSTEAD", "I SHOULD HAVE KNOWN BETTER", "AND I LOVE HER", "IF I FELL", "CANT BUY ME LOVE", "THINGS WE SAID TODAY", "ANY TIME AT ALL", "MATCHBOX", "SLOW DOWN", "TELL ME WHY", "NO REPLY", "IM A LOSER", "BABYS IN BLACK", "ROCK AND ROLL MUSIC", "ILL FOLLOW THE SUN", "MR MOONLIGHT", "HONEY DONT", "ILL BE BACK", "SHES A WOMAN", "I FEEL FINE", "PLEASE PLEASE ME", "EIGHT DAYS A WEEK", "WORDS OF LOVE", "YES IT IS", "DIZZY MISS LIZZY", "HELP", "I NEED YOU", "ANOTHER GIRL", "TICKET TO RIDE", "YOURE GOING TO LOSE THAT GIRL", "IVE JUST SEEN A FACE", "NORWEGIAN WOOD", "THINK FOR YOURSELF", "MICHELLE", "GIRL", "IN MY LIFE", "WAIT", "DRIVE MY CAR", "NOWHERE MAN", "YESTERDAY", "ACT NATURALLY", "WE CAN WORK IT OUT", "DAY TRIPPER", "ELEANOR RIGBY", "YELLOW SUBMARINE", "GOOD DAY SUNSHINE", "SHES LEAVING HOME", "WHEN IM SIXTY FOUR", "LOVELY RITA", "A DAY IN THE LIFE", "MAGICAL MYSTERY TOUR", "THE FOOL ON THE HILL", "BLUE JAY WAY", "I AM THE WALRUS", "HELLO GOODBYE", "STRAWBERRY FIELDS FOREVER", "PENNY LANE", "BABY YOURE A RICH MAN", "ALL YOU NEED IS LOVE", "BACK IN THE USSR", "OB LA DI OB LA DA", "BLACKBIRD", "ROCKY RACCOON", "DONT PASS ME BY", "JULIA", "YELLOW SUBMARINE", "ALL TOGETHER NOW", "COME TOGETHER", "SOMETHING", "HERE COMES THE SUN", "REVOLUTION", "HEY JUDE", "ACROSS THE UNIVERSE", "LET IT BE"]
      }, 
  { 
      cat: "Broadway",
      sel: false,
      parent: "Music",
      numOfItems: 0,
      items: ["WEST SIDE STORY", "LES MISERABLES", "MARIA", "CAMELOT", "OKLAHOMA", "OH WHAT A BEAUTIFUL MORNING", "CAMELOT", "SWEENY TODD", "THE LION KING", "CATS", "GODSPELL", "MAN OF LA MANCHA", "THE UNSINKABLE MOLLY BROWN", "INTO THE WOODS", "RAGTIME", "ANYTHING GOES", "RENT", "THE PHANTOM OF THE OPERA", "THE SOUND OF MUSIC", "HELLO DOLLY", "CHICAGO", "THE MUSIC MAN", "SOUTH PACIFIC", "CABARET", "WICKED", "A LITTLE NIGHT MUSIC", "MY FAIR LADY", "A CHORUS LINE", "GYPSY", "FIDDLER ON THE ROOF", "THEY CALL THE WIND MARIAH", "THE MUSIC OF THE NIGHT", "BIG SPENDER", "POPULAR", "COMEDY TONIGHT", "TRADITION", "MY FAVORITE THINGS", "EDELWEISS", "IF EVER I WOULD LEAVE YOU", "GET ME TO THE CHURCH ON TIME", "NIGHT AND DAY", "PINBALL WIZARD", "TRY TO REMEMBER", "BRING HIM HOME", "MATCHMAKER MATCHMAKER", "SHALL WE DANCE", "ALL THAT JAZZ", "AMERICA", "WILKOMMEN", "DONT CRY FOR ME ARGENTINA", "TONIGHT", "ON THE STREET WHERE YOU LIVE", "MEMORY", "I DREAMED A DREAM", "SOME ENCHANTED EVENING", "IF I WERE A RICH MAN", "SEND IN THE CLOWNS", "YOULL NEVER WALK ALONE", "ONE DAY MORE", "THE IMPOSSIBLE DREAM", "ANDREW LLOYD WEBER", "STEPHEN SONDHEIM", "RICHARD RODGERS", "OSCAR HAMMERSTEIN", "ALAN JAY LERNER", "WOULDNT IT BE LOVERLY"]
    },  
  { 
      cat: "Classical",
      sel: false,
      parent: "Music",
      numOfItems: 0,
      items: ["JOHANN SEBASTIAN BACH", "FRANZ JOSEPH HAYDN", "GEORGE FREDRICK HANDEL", "ROBERT SCHUMAN", "LUDWIG VAN BEETHOVEN", "FRANZ SHCUBERT", "FREDERIC CHOPIN", "ODE TO JOY", "MOONLIGHT SONATA", "HEILIGER DANKGESANG", "FRANZ LIZST", "HUNGARIAN RHAPSODIES", "BRANDENBURG CONCERTOS", "CLAUDE DEBUSSY", "MODEST MUSSORGSKY", "NIGHT ON BALD MOUNTAIN", "HAMMERKLAVIER", "VLADIMIR HOROWITZ", "THE EMPEROR CONCERTO", "ARTUR RUBINSTEIN", "JASCHA HEIFETZ", "SERGEI RACHMANINOFF", "PETER ILYICH TCHAIKOVSKY", "SWAN LAKE", "SLEEPING BEAUTY", "THE NUTCRACKER SUITE", "CLAIR DE LUNE", "BOLERO", "MAURICE RAVEL", "WOLFGANG AMADEUS MOZART", "THE MARRIAGE OF FIGARO", "DON GIOVANNI", "CARMEN", "GEORGE BIZET", "LEONARD BERNSTEIN", "ANTONIN DVORAK", "GIACCHINO ROSSINI", "ENRICO CARUSO", "JUSSI BJORLING", "LUCIANO PAVAROTTI", "MARIA CALLAS", "LA BOHEME", "TURONDOT", "GIACAMO PUCCINI", "FUGUE", "SYMPHONY", "CONCERTO", "SONATA", "RITE OF SPRING", "EROICA", "GUSTAV MAHLER", "ANTON BRUCKNER", "SYMPHONY OF A THOUSAND", "RESURRECTTION SYMPHONY"],
    },       
  { 
    cat: "Hits of the 60's",
    sel: false,
    parent: "Music",
    numOfItems: 0,
    items: ["EL PASO", "RUNNING BEAR", "TEEN ANGEL", "THEME FROM A SUMMER PLACE", "CATHYS CLOWN", "ITS NOW OR NEVER", "THE TWIST", "SAVE THE LAST DANCE FOR ME", "GEORGIA ON MY MIND", "STAY", "ARE YOU LONESOME TONIGHT", "WILL YOU LOVE ME TOMORROW", "BLUE MOON", "RUNAWAY", "MOTHER IN LAW", "TRAVELIN MAN", "TOSSIN AND TURNIN", "MICHAEL", "TAKE GOOD CARE OF MY BABY", "HIT THE ROAD JACK", "RUNAROUND SUE", "BIG BAD JOHN", "PLEASE MR POSTMAN", "THE LION SLEEPS TONIGHT", "DUKE OF EARL", "JOHNNY ANGEL", "SOLDIER BOY", "I CANT STOP LOVING YOU", "ROSES ARE RED", "BREAKING UP IS HARD TO DO", "THE LOCO MOTION", "SHERRY", "MONSTER MASH", "HES A REBEL", "BIG GIRLS DONT CRY", "GO AWAY LITTLE GIRL", "WALK RIGHT IN", "HEY PAULA", "WALK LIKE A MAN", "OUR DAY WILL COME", "HES SO FINE", "I WILL FOLLOW HIM", "ITS MY PARTY", "EASIER SAID THAN DONE", "SURF CITY", "MY BOYFRIENDS BACK", "BLUE VELVET", "DOMINIQUE", "I WANT TO HOLD YOUR HAND", "SHE LOVES YOU", "CANT BUY ME LOVE", "HELLO DOLLY", "MY GUY", "LOVE ME DO", "CHAPEL OF LOVE", "A WORLD WITHOUT LOVE", "I GET AROUND", "RAG DOLL", "A HARD DAYS NIGHT", "EVERYBODY LOVES SOMEBODY", "WHERE DID OUR LOVE GO", "THE HOUSE OF THE RISING SUN", "OH PRETTY WOMAN", "DO WAH DIDDY DIDDY", "BABY LOVE", "LEADER OF THE PACK", "RINGO", "MR LONELY", "COME SEE ABOUT ME", "I FEEL FINE", "DOWNTOWN", "YOUVE LOST THAT LOVIN FEELING", "THIS DIAMOND RING", "MY GIRL", "EIGHT DAYS A WEEK", "STOP IN THE NAME OF LOVE", "IM TELLING YOU NOW", "MRS BROWN YOUVE GOT A LOVELY DAUGHTER", "TICKET TO RIDE",
      "HELP ME RHONDA", "BACK IN MY ARMS AGAIN", "I CANT HELP MYSELF", "MR TAMBOURINE MAN", "SATISFACTION", "IM HENRY VIII I AM", "I GOT YOU BABE", "HELP", "EVE OF DESTRUCTION", "HANG ON SLOOPY", "YESTERDAY", "GET OFF MY CLOUD", "I HEAR A SYMPHONY", "TURN TURN TURN", "OVER AND OVER", "THE SOUND OF SILENCE", "WE CAN WORK IT OUT", "MY LOVE", "LIGHTNIN STRIKES", "THESE BOOTS ARE MADE FOR WALKIN", "THE BALLAD OF THE GREEN BERETS", "SOUL AND INSPIRATION", "GOOD LOVIN", "MONDAY MONDAY", "WHEN A MAN LOVES A WOMAN", "PAINT IT BLACK", "PAPERBACK WRITER", "STRANGERS IN THE NIGHT", "HANKY PANKY", "WILD THING", "SUMMER IN THE CITY", "SUNSHINE SUPERMAN", "YOU CANT HURRY LOVE", "CHERISH", "REACH OUT ILL BE THERE", "LAST TRAIN TO CLARKSVILLE", "YOU KEEP ME HANGIN ON", "WINCHESTER CATHEDRAL", "GOOD VIBRATIONS", "IM A BELIEVER", "KIND OF A DRAG", "PENNY LANE", "HAPPY TOGETHER", "SOMETHIN STUPID", "THE HAPPENING", "GROOVIN", "RESPECT", "WINDY", "LIGHT MY FIRE", "ALL YOU NEED IS LOVE", "ODE TO BILLIE JOE", "THE LETTER", "TO SIR WITH LOVE", "INCENSE AND PEPPERMINTS", "DAYDREAM BELIEVER", "HELLO GOODBYE", "JUDY IN DISGUISE", "GREEN TAMBOURINE", "LOVE IS BLUE", "THE DOCK OF THE BAY", "HONEY", "TIGHTEN UP", "MRS ROBINSON", "THIS GUYS IN LOVE WITH YOU", "GRAZING IN THE GRASS", "HELLO I LOVE YOU", "PEOPLE GOT TO BE FREE", "HARPER VALLEY PTA", "HEY JUDE", "LOVE CHILD", "I HEARD IT THROUGH THE GRAPEVINE", "CRIMSON AND CLOVER", "EVERYDAY PEOPLE", "DIZZY", "AQUARIUS", "GET BACK", "HONKY TONK WOMEN", "SUGAR SUGAR", "I CANT GET NEXT TO YOU", "SUSPICIOUS MINDS", "COME TOGETHER", "LEAVING ON A JET PLANE", "SOMEDAY WELL BE TOGETHER"]
    },  
    { 
      cat: "Hits of the 70's",
      sel: false,
      parent: "Music",
      numOfItems: 0,
      items: ["VENUS", "BRIDGE OVER TROUBLED WATER", "LET IT BE", "AMERICAN WOMAN", "EVERYTHING IS BEAUTIFUL", "THE LONG AND WINDING ROAD", "MAMA TOLD ME", "CLOSE TO YOU", "MAKE IT WITH YOU", "AINT NO MOUNTAIN HIGH ENOUGH", "CRACKLIN ROSIE", "I THINK I LOVE YOU", "THE TEARS OF A CLOWN", "MY SWEET LORD", "KNOCK THREE TIMES", "ME AND BOBBY MCGEE", "JUST MY IMAGINATION", "JOY TO THE WORLD", "BROWN SUGAR", "ITS TOO LATE", "INDIAN RESERVATION", "YOUVE GOT A FRIEND", "HOW CAN YOU MEND A BROKEN HEART", "UNCLE ALBERT ADMIRAL HALSEY", "MAGGIE MAY", "GYPSYS TRAMPS AND THIEVES", "THEME FROM SHAFT", "FAMILY AFFAIR", "BRAND NEW KEY", "AMERICAN PIE", "HEART OF GOLD", "A HORSE WITH NO NAME", "CANDY MAN", "BRANDY", "BABY DONT GET HOOKED ON ME","I CAN SEE CLEARLY NOW", "PAPA WAS A ROLLIN STONE", "I AM WOMAN", "YOURE SO VAIN", "SUPERSTITION", "CROCODILE ROCK", "KILLING ME SOFTLY", "LOVE TRAIN", "TIE A YELLOW RIBBON", "YOU ARE THE SUNSHINE OF MY LIFE", "MY LOVE", "BAD BAD LEROY BROWN", "THE MORNING AFTER", "TOUCH ME IN THE MORNING", "DELTA DAWN", "WERE AN AMERICAN BAND", "HALF BREED", "ANGIE", "MIDNIGHT TRAIN TO GEORGIA", "TOP OF THE WORLD", "THE MOST BEAUTIFUL GIRL", "TIME IN A BOTTLE", "YOURE SIXTEEN", "SEASONS IN THE SUN", "SUNSHINE ON MY SHOULDERS", "HOOKED ON A FEELING", "BENNIE AND THE JETS", "THE LOCO MOTION", "BILLY DONT BE A HERO", "SUNDOWN", "ROCK THE BOAT", "ANNIES SONG", "THE NIGHT CHICAGO DIED", "I SHOT THE SHERIFF", "ROCK ME GENTLY", "I HONESTLY LOVE YOU", "NOTHING FROM NOTHING", "YOU AINT SEEN NOTHING YET", "KUNG FU FIGHTING", "CATS IN THE CRADLE", "LUCY IN THE SKY WITH DIAMONDS", "MANDY", "PLEASE MR POSTMAN", "HAVE YOU NEVER BEEN MELLOW", "THANK GOD IM A COUNTRY BOY", "SISTER GOLDEN HAIR", "LOVE WILL KEEP US TOGETHER", "LISTEN TO WHAT THE MAN SAID", "JIVE TALKIN", "GET DOWN TONIGHT", "RHINESTONE COWBOY", "SATURDAY NIGHT", "I WRITE THE SONGS", "WELCOME BACK", "AFTERNOON DELIGHT", "DONT GO BREAING MY HEART", "PLAY THAT FUNKY MUSIC", "TONIGHTS THE NIGHT", "DANCING QUEEN", "HOTEL CALIFORNIA", "YOU LIGHT UP MY LIFE", "HOW DEEP IS YOUR LOVE", "STAYIN ALIVE", "WITH A LITTLE LUCK", "THREE TIMES A LADY", "YOU DONT BRING ME FLOWERS", "TOO MUCH HEAVEN", "DA YA THINK IM SEXY", "I WILL SURVIVE", "WHAT A FOOL BELIEVES", "HEART OF GLASS", "REUNITED", "MY SHARONA", "THE PINA COLADA SONG", "BOHEMIAN RHAPSODY"]
      },  
      { 
        cat: "Lightfoot Songs",
          sel: false,
          parent: "Music",
          numOfItems: 0,
          items: ["SIT DOWN YOUNG STRANGER", "IF YOU COULD READ MY MIND", "TEN DEGREES AND GETTING COLDER", "MIGUEL", "GO MY WAY", "SUMMER SIDE OF LIFE", "COTTON JENNY", "TALKING IN YOUR SLEEP", "SAME OLD LOVERMAN", "REDWOOD HILL", "LOVE AND MAPLE SYRUP", "CABARET", "DON QUIXOTE", "CHRISTIAN ISLAND", "LOOKING AT THE RAIN", "ORDINARY MAN", "BRAVE MOUNTAINEERS", "ODE TO BIG BLUE", "SECOND CUP OF COFFEE", "BEAUTIFUL", "SUNDOWN", "CANANDIAN RAILROAD TRILOGY", "ALBERTA BOUND", "CAREFREE HIGHWAY", "RAINY DAY PEOPLE", "THE WRECK OF THE EDMUND FITZGERALD", "HOME FROM THE FOREST", "THE MOUNTAINS AND MARYANN"],
        },   
        { 
          cat: "Lightfoot Lyrics",
            sel: false,
            parent: "Music",
            numOfItems: 0,
            items: ["OH THE NEON LIGHTS WERE FLASHING", "AND THE ICY WIND DID BLOW", "THE DRIZZLE TURNED TO SNOW", "THE WINE WAS RUNNIN LOW", "AS UPON HIS COT HE LAY", "SHE TOUCHED HIS GRIZZLED FINGERS", "THE DAWN WILL COME NO MORE", "IM STANDIN IN THE DOORWAY", "MY HEAD BOWED IN MY HANDS", "AND TELL US WHO YOU ARE", "IVE WALKED DOWN BY THE SEA", "MY MOTHERS EYES GROW MISTY", "YOU MUST WEAR THE CROWN OF THORNS", "DOES ANYONE LOVE ME", "WHAT A TALE MY THOUGHTS COULD TELL", "JUST LIKE AN OLD TIME MOVIE", "BOUT A GHOST FROM A WISHIN WELL", "A GHOST THAT YOU CANT SEE", "JUST LIKE A PAPERBACK NOVEL", "THE HERO WOULD BE ME", "BUT HEROES OFTEN FAIL", "A MOVIE QUEEN TO PLAY THE SCENE", "DOWN BY BOLDER DAM THAT DAY", "OH MY SWEET MIGUEL", "I WILL NEVER TELL", "LISTEN TO THE BELL", "OF MY POVERTY", "YOU MUST NEVER TELL", "A LAWMAN CAME TO CAPTURE HIM", "OH MIGUELL THE MOTHER CRIED", "YOU MUST RUN SON OR YOULL DIE", "ILL LOVE YOU TIL I DIE", "ITS THE ONLY WAY TO GO", "IS THERE ANYTHING THAT I CAN DO", "ITS A NAME I DONT RECALL", "I HEARD YOU SOFTLY WHISPER", "BOUT ANYTHING AT ALL", "THROUGH THE WOODLAND", "THROUGH THE VALLEY", "HE IS WILD BUT HE IS MELLOW", "TAKES A RUSTY SWORD INTO HIS HAND", "TIL HE CAN SHOUT NO MORE", "HE IS WISE BUT HE IS MEEK", "PRAIRIE LIGHTS ARE BURNIN BRIGHT", "ITS GOOD TO BE ALBERTA BOUND", "OH THE SKYLINE OF TORONTO","NEON LIGHTS WERE FLASHING", "THE ICY WIND DID BLOW", "DRIZZLE TURNED TO SNOW", "WINE WAS RUNNIN LOW", "UPON HIS COT HE LAY", "HIS GRIZZLED FINGERS", "WEAR THE CROWN OF THORNS", "DOES ANYONE LOVE ME", "MY THOUGHTS COULD TELL", "LIKE AN OLD TIME MOVIE", "A GHOST FROM A WISHIN WELL", "LIKE A PAPERBACK NOVEL", "BUT HEROES OFTEN FAIL", "A MOVIE QUEEN", "TO PLAY THE SCENE", "DOWN BY BOLDER DAM THAT DAY", "OH MY SWEET MIGUEL", "I WILL NEVER TELL", "LISTEN TO THE BELL", "OF MY POVERTY", "YOU MUST NEVER TELL", "A LAWMAN CAME", "TO CAPTURE HIM", "ILL LOVE YOU TIL I DIE", "ITS THE ONLY WAY TO GO", "A NAME I DONT RECALL", "LOOKING AT THE WIND", "LOOKING AT THE DAWN", "BORN IN THE COUNTRY", "AND I NEED TO BE THERE", "LIKE BRAVE MOUNTAINEERS"],
          },             
      { 
        cat: "Popular",
          sel: false,
          parent: "Music",
          numOfItems: 0,
          items: ["THE BEATLES", "THE ROLLING STONES", "BUDDY HOLLY", "ROY ORBISON", "DION", "SIMON AND GARFUNKLE", "CAT STEVENS", "ELTON JOHN", "NEIL DIAMOND", "JUDY COLLINS", "THE FOUR TOPS", "THE TEMPTATIONS", "THE SUPREMES", "STRAWBERRY ALARM CLOCK", "DRIFTERS", "COASTERS", "IN THE STILL OF THE NIGHT", "THE BEACH BOYS", "THE DAVE CLARK FIVE", "THE HOLLIES", "CREEDENCE CLEARWATER REVIVAL", "THE EAGLES", "DEEP PURPLE", "QUEEN", "RADIO GA GA", "WE ARE THE CHAMPIONS", "WE WILL ROCK YOU", "I GET AROUND", "GOOD VIBRATIONS", "HELP ME RHONDA", "WILD WORLD", "PEACE TRAIN", "RUBYLOVE", "PROUD MARY", "WHOLL STOP THE RAIN", "LOVE POTION NUMBER NINE", "POISON IVY", "CHARLIE BROWN", "UP ON THE ROOF", "RUNAROUND SUE", "DREAM DREAM DREAM", "WAKE UP LITTLE SUZIE", "SMOKE ON THE WATER", "BUDDY HOLLY", "PEGGY SUE", "THE MOODY BLUES", "NIGHTS IN WHITE SATIN", "HOTEL CALIFORNIA", "GORDON LIGHTFOOT", "IF YOU COULD READ MY MIND", "THE EAGLES"],
        }, 
        { 
          cat: "Others",
            sel: false,
            parent: "Music",
            numOfItems: 0,
            items: ["ELMER BERNSTEIN", "MIKLOS ROZSA", "MAX STEINER", "ELLA FITZGERALD", "FRANK SINATRA", "TONY BENNET", "ENNIO MORRICONE", "BERNARD HERRMANN", "BEGIN THE BEGUINE", "HEART AND SOUL", "HOAGY CARMICHAEL", "STARDUST", "TAKE THE A TRAIN", "CHATTANOOGA CHOO CHOO", "GLENN MILLER", "JOHN WILLIAMS"],
          }, 
  

  { 
    cat: "Presidents",
    sel: false,
    parent: "",
    numOfItems: 0,
    items: ["GEORGE WASHINGTON", "JOHN ADAMS", "THOMAS JEFFERSON", "JAMES MADISON", "JAMES MONROE", "JOHN QUINCY ADAMS", "ANDREW JACKSON", "MARTIN VAN BUREN", "WILLIAM HENRY HARRISON", "JOHN TYLER", "JAMES K POLK", 
    "ZACHARY TAYLOR", "MILLARD FILLMORE", "FRANKLIN PIERCE", "JAMES BUCHANAN", "ABRAHAM LINCOLN", "ANDREW JOHNSON", "ULYSSES S GRANT", "RUTHERFORD B HAYES", "JAMES GARFIELD", "CHESTER A ARTHUR", "GROVER CLEVELAND", "BENJAMIN HARRISON", "WILLIAM MCKINLEY", "THEODORE ROOSEVELT", "WILLIAM HOWARD TAFT", "WOODROW WILSON", "WARREN G HARDING", "CALVIN COOLIDGE", "HERBERT HOOVER", "FRANKLIN D ROOSEVELT", "HARRY TRUMAN", "DWIGHT EISENHOWER", "JOHN F KENNEDY", "LYNDON JOHNSON", "RICHARD NIXON", "GERALD FORD", "JIMMY CARTER", "RONALD REAGAN", "GEORGE H W BUSH", "BILL CLINTON", "GEORGE W BUSH", "BARACK OBAMA", "DONALD TRUMP", "JOE BIDEN"]
  },
  { 
    cat: "Yankees",
    sel: false,
    parent: "Sports",
    numOfItems: 0,
    items: ["BABE RUTH", "LOU GEHRIG", "JOE DIMAGGIO", "MICKEY MANTLE", "WHITEY FORD", "DEREK JETER", 
  "MARIANO RIVERA", "JOE MCCARTHY", "MILLER HUGGINS", "YOGI BERRA", "ELSTON HOWARD", "JOE PEPITONE", "BOBBY RICHARDSON", "CLETE BOYER", "TONY KUBEK", "TOM TRESH", "ROGER MARIS", "PHIL LINZ", "HECTOR LOPEZ", "JOHNNY BLANCHARD", "PEDRO GONZALEZ", "JAKE GIBBS", "MIKE HEGAN", "ROGER REPOZ", "JIM BOUTON", "AL DOWNING", "MEL STOTTLEMYRE", "RALPH TERRY", "STAN WILLIAMS", "PETE MIKKELSEN", "HAL RENIFF", "BILL STAFFORD", "STEVE HAMILTON", "PEDRO RAMOS", "FRANK CROSETTI", "STEVE BARBER", "FRITZ PETERSON", "THAD TILLOTSON", "DOOLEY WOMACK", "FRANK FERNANDEZ", "RUBEN AMARO", "HORACE CLARKE", "DICK HOWSER", "FRANK TEPEDINO", "BILL ROBINSON", "STEVE WHITAKER", "ROY WHITE", "RALPH HOUK", "TONY LAZZERI", "BOB MEUSEL", "EARL COMBS", "WAITE HOYT", "HERB PENNOCK", "BILL DICKEY", "RED ROLFE", "RED RUFFING", "LEFTY GOMEZ", "CASEY STENGEL", "GENE WOODLING", "JOHNNY MIZE", "TOMMY HENRICH", "VIC RASCHI", "ALLIE REYNOLDS", "BILL SKOWRON", "GIL MCDOUGALD", "BOB TURLEY", "RALPH TERRY", "BOBBY SHANTZ", "LUIS ARROYO", "BOBBY MURCER", "ROCKY COLAVITO", "STAN BAHNSEN", "CHRIS CHAMBLISS", "WILLIE RANDOLPH", "THURMAN MUNSON", "BUCKY DENT", "GRAIG NETTLES", "MICKEY RIVERS", "LOU PINIELLA", "CATFISH HUNTER", "ED FIGUROA", "GOOSE GOSSAGE", "SPARKY LYLE", "DON MATTINGLY", "DAVE WINFIELD", "REGGIE JACKSON", "ELLIOT MADDOX", "ANDY PETTITTE", "JORGE POSADA", "DAVID ROBERTSON", "PAUL ONEILL", "BERNIE WILLIAMS", "STEVE SAX", "CHUCK KNOBLAUCH", "ROGER CLEMENS", "DAVID CONE", "BILL WHITE", "FRANK MESSER"],
  },
  { 
    cat: "Landrys Cowboys",
    sel: false,
    parent: "Sports",
    numOfItems: 0,
    items: ["TOM LANDRY", "GIL BRANDT", "TEX SCHRAMM", "CLINT MURCHISON", "BOB HAYES", "BOB LILY", "DANDY DON MEREDITH", "CRAIG MORTON", "DAN REEVES", "DON PERKINS", "LES SHY", "WALT GARRISON", "PETTIS NORMAN", "PETE GENT", "LANCE RENTZEL", "RALPH NEELY", "MIKE CLARK", "RON WIDBY", "JETHRO PUGH", "GEORGE ANDRIE", "CHUCK HOWLEY", "LEE ROY JORDAN", "LARRY COLE", "MIKE GAECHTER", "CORNELL GREEN", "MEL RENFRO", "WILLIE TOWNES", "TONY LISCIO", "JOHN NILAND", "DAVE EDWARDS", "D D LEWIS", "RAYFIELD WRIGHT","ROGER STAUBACH", "CLINT LONGLEY", "ROBERT NEWHOUSE", "CALVIN HILL", "DUANE THOMAS", "PRESTON PEARSON", "DOUG DENNISON", "GOLDEN RICHARDS", "SCOTT LAIDLAW", "DREW PEARSON", "BILLY JOE DUPREE", "BOB BREUNIG", "THOMAS HENDERSON", "CHARLIE WATERS", "TONI FRITSCH", "RANDY WHITE", "BILL GREGORY", "CLIFF HARRIS", "MARK WASHINGTON", "ED TOO TALL JONES", "RANDY HUGHES", "PAT DONOVAN", "HARVEY MARTIN", "JEAN FUGETT", "DANNY WHITE", "TONY DORSETT", "RON SPRINGS", "TONY HILL", "BUTCH JOHNSON", "DOUG COSBIE", "RAFAEL SEPTIEN", "DENNIS THURMAN", "JOHN DUTTON", "MIKE HEGMAN", "AARON MITCHELL", "BENNY BARNES", "TOM RAFFERTY", "HERSCHEL WALKER", "MICHAEL IRVIN", "NATE NEWTON", "EVERSON WALLS", "BILL BATES", "JIM JEFFCOAT", "KEN NORTON JR", "CLAXTON WELCH", "LANCE ALWORTH", "REGGIE RUCKER", "IKE THOMAS", "HERB ADDERLEY", "JOHN FITZGERALD", "RODNEY WALLACE", "BILL GREGORY", "TODY SMITH", "PAT TOOMAY", "ERNIE STAUTNER"],
  },

  { 
    cat: "States",
    sel: false,
    parent: "",
    numOfItems: 0,
    items: ["ALABAMA", "ALASKA", "ARIZONA", "ARKANSAS", "CALIFORNIA", "COLORADO", "CONNECTICUT", "DELAWARE", "FLORIDA", "GEORGIA", "HAWAII", "IDAHO", "ILLINOIS", "INDIANA", "IOWA", "KANSAS", "KENTUCKY", "LOUISIANA", "MAINE", "MARYLAND", "MASSACHUSETTS", "MICHIGAN", "MINNESOTA", "MISSISSIPPI", "MISSOURI", "MONTANA", "NEBRASKA", "NEVADA", "NEW HAMPSHIRE", "NEW JERSEY", "NEW MEXICO", "NEW YORK", "NORTH CAROLINA", "NORTH DAKOTA", "OHIO", "OKLAHOMA", "OREGON", "PENNSYLVANIA", "RHODE ISLAND", "SOUTH CAROLINA", "SOUTH DAKOTA", "TENNESSEE", "TEXAS", "UTAH", "VERMONT", "VIRGINIA", "WASHINGTON", "WEST VIRGINIA", "WISCONSIN", "WYOMING"]
  },
  { 
    cat: "State Capitals",
    sel: false,
    parent: "",
    numOfItems: 0,
    items: ["MONTGOMERY", "JUNEAU", "PHOENIX", "LITTLE ROCK", "SACRAMENTO", "DENVER", "HARTFORD", "DOVER", "TALLAHASSEE", "ATLANTA", "HONOLULU", "BOISE", "SPRINGFIELD", "INDIANAPOLIS", "DES MOINES", "TOPEKA", "FRANKFORT", "BATON ROUGE", "AUGUSTA", "ANNAPOLIS", "BOSTON", "LANSING", "ST PAUL", "JACKSON", "JEFFERSON CITY", "HELENA", "LINCOLN", "CARSON CITY", "CONCORD", "TRENTON", "SANTA FE", "ALBANY", "RALEIGH", "BISMARK", "COLUMBUS", "OKLAHOMA CITY", "SALEM", "HARRISBURG", "PROVIDENCE", "COLUMBIA", "PIERRE", "NASHVILLE", "AUSTIN", "SALT LAKE CITY", "MONTPELIER", "RICHMOND", "OLYMPIA", "CHARLESTON", "MADISON", "CHEYENNE"]
    },
    { 
      cat: "TV Shows",
      sel: false,
      parent: "",
      numOfItems: 0,
      items: ["THE ADVENTURES OF SUPERMAN", "I LOVE LUCY", "LEAVE IT TO BEAVER", "FATHER KNOWS BEST", "THE DANNY THOMAS SHOW", "THE HONEYMOONERS", "BURNS AND ALLEN", "OZZIE AND HARRIET", "HOWDY DOODY", "THE LONE RANGER", "THE ROY ROGERS SHOW", "LASSIE", "GUNSMOKE", "PERRY MASON", "MAVERICK", "CHEYENNE", "THE DONNA REED SHOW", "OUR MISS BROOKS", "AMOS N ANDY", "WAGON TRAIN", "HAVE GUN WILL TRAVEL", "THE ANDY GRIFFITH SHOW", "THE REAL MCCOYS", "RAWHIDE", "CANDID CAMERA", "THE UNTOUCHABLES", "THE PRICE IS RIGHT","THE JACK BENNY SHOW", "DENNIS THE MENACE", "MY THREE SONS", "THE ED SULLIVAN SHOW", "BONANZA", "THE FLINTSTONES", "THE RED SKELTON SHOW", "GENERAL ELECTRIC THEATER", "CHECKMATE", "WHATS MY LINE", "THE MANY LOVES OF DOBIE GILLIS", "THE RIFLEMAN", "PETER GUNN", "HAZEL", "DR KILDARE", "SING ALONG WITH MITCH", "THE BEVERLY HILLBILLIES", "THE LUCY SHOW", "BEN CASEY", "THE DICK VAN DYKE SHOW", "WHATS MY LINE", "IVE GOT A SECRET", "THE JACKIE GLEASON SHOW", "THE DEFENDERS", "TO TELL THE TRUTH", "WAGON TRAIN", "THE VIRGINIAN", "PETTICOAT JUNCTION", "MY FAVORITE MARTIAN", "THE PATTY DUKE SHOW", "MCHALES NAVY", "THE FUGITIVE", "THE DANNY KAYE SHOW", "BEWITCHED", "GOMER PYLE USMC", "COMBAT", "BRANDED", "THE MUNSTERS", "GILLIGANS ISLAND", "PEYTON PLACE", "THE ADDAMS FAMILY", "FLIPPER", "THE LAWRENCE WELK SHOW","BATMAN", "HOGANS HEROES", "GREEN ACRES", "GET SMART", "THE MAN FROM UNCLE", "DAKTARI", "THE WILD WILD WEST", "DANIEL BOONE", "I DREAM OF JEANNIE", "FAMILY AFFAIR", "THE SMOTHERS BROTHERS", "DRAGNET", "TARZAN", "I SPY", "THE FBI", "GENTLE BEN", "ROWAN AND MARTINS LAUGH IN", "IRONSIDE", "THE CAROL BURNETT SHOW", "IT TAKES A THIEF", "MAYBERRY RFD", "JULIA", "HERES LUCY", "MISSION IMPOSSIBLE", "THE MOD SQUAD", "MARCUS WELBY MD", "THE JIM NABORS HOUR", "HAWAII FIVE O", "HEE HAW", "MANNIX", "ALL IN THE FAMILY", "THE FLIP WILSON SHOW", "SANFORD AND SON", "THE MARY TYLER MOORE SHOW", "MEDICAL CENTER", "THE PARTRIDGE FAMILY", "CANNON", "MAUDE", "BRIDGET LOVES BERNIE", "THE BOB NEWHART SHOW", "THE WALTONS", "THE ROOKIES", "BARNABY JONES", "KUNG FU", "KOJAK", "HAPPY DAYS", "GOOD TIMES", "THE STREETS OF SAN FRANCISCO", "CHICO AND THE MAN", "THE JEFFERSONS", "RHODA", "THE ROCKFORD FILES", "LITTLE HOUSE ON THE PRAIRIE", "POLICE WOMAN", "EMERGENCY", "LAVERNE AND SHIRLEY", "THE BIONIC WOMAN", "THE SIX MILLION DOLLAR MAN", "ONE DAY AT A TIME", "STARSKY AND HUTCH", "BARETTA", "DONNY AND MARIE", "POLICE WOMAN", "CHARLIES ANGELS", "THREES COMPANY", "WELCOME BACK KOTTER", "BARNEY MILLER", "EIGHT IS ENOUGH", "WHATS HAPPENING", "THE TONY RANDALL SHOW", "ALICE", "THE LOVE BOAT", "FANTASY ISLAND", "THE INCREDIBLE HULK", "MORK AND MINDY", "THE DUKES OF HAZZARD", "CHIPS", "DIFFERENT STROKES", "LOU GRANT", "DALLAS", "ARCHIE BUNKERS PLACE", "TRAPPER JOHN MD", "WKRP IN CINCINNATI", "BENSON", "KNOTS LANDING", "THE ORIGINAL AMATEUR HOUR", "YOUR SHOW OF SHOWS", "HOPALONG CASSIDY", "YOU BET YOUR LIFE", "RACKET SQUAD", "THE LIFE OF RILEY", "THE MILTON BERLE SHOW", "I MARRIED JOAN", "THIS IS YOUR LIFE", "THE MILLIONAIRE", "THE ADVENTURES OF RIN TIN TIN", "TOPPER", "THE LORETTA YOUNG SHOW", "MY LITTLE MARGIE", "ALFRED HITCHCOCK PRESENTS", "THE GALE STORM SHOW", "ZORRO", "TALES OF WELLS FARGO", "WANTED DEAD OR ALIVE", "THE ANN SOTHERN SHOW", "MAGNUM PI", "HART TO HART", "TOO CLOSE FROM COMFORT", "DYNASTY", "THE FALL GUY", "HILL STREET BLUES", "TJ HOOKER", "SIMON AND SIMON", "THE A TEAM", "NEWHART", "ONE DAY AT A TIME", "KATE AND ALLIE", "HOTEL", "CAGNEY AND LACEY", "SCARECROW AND MRS KING", "WEBSTER", "KNIGHT RIDER", "FAMILY TIES", "MURDER SHE WROTE", "HIGHWAY TO HEAVEN", "NIGHT COURT", "REMINGTON STEELE", "CHEERS", "THE GOLDEN GIRLS", "MIAMI VICE", "GROWING PAINS", "MOONLIGHTING", "MATLOCK", "HUNTER", "HEAD OF THE CLASS", "THE WONDER YEARS", "IN THE HEAT OF THE NIGHT", "ROSEANNE", "EMPTY NEST", "UNSOLVED MYSTERIES", "FULL HOUSE", "DESIGNING WOMEN", "MURPHY BROWN", "DOOGIE HOWSER MD", "RERUN", "MR ROARKE", "TATTOO"]
      },
  { 
        cat: "TV Characters",
        sel: false,
        parent: "",
        numOfItems: 0,
        items: ["CLARK KENT", "LOIS LANE", "JIMMY OLSEN", "PERRY WHITE", "INSPECTOR HENDERSON", "MARA VAN CLEAVER", "SYLVESTER J SUPERMAN", "PROFESSOR PEPPERWINKLE","LUCY RICARDO", "RICKY RICARDO", "FRED MERTZ", "ETHEL MERTZ", "BEAVER CLEAVER", "WARD CLEAVER", "JUNE CLEAVER", "WALLY CLEAVER", "EDDIE HASKELL", "LUMPY RUTHERFORD", "RALPH KRAMDEN", "ALICE KRAMDEN", "ED NORTON", "TRIXIE NORTON", "TONTO", "MATT DILLON", "PERRY MASON", "HAMILTON BURGER", "DELLA STREET", "PAUL DRAKE", "LT ARTHUR TRAGG", "ANDY TAYLOR", "OPIE TAYLOR", "BARNEY FIFE", "BEA TAYLOR", "GOMER PYLE", "GOOBER PYLE", "HELEN CRUMP", "BEN CARTWRIGHT", "ADAM CARTWRIGHT", "HOSS CARTWRIGHT", "JOE CARTWRIGHT", "FRED FLINTSTONE", "WILMA FLINTSTONE", "BARNEY RUBBLE", "BETTY RUBBLE", "PEBBLES", "BAM BAM", "DOBIE GILLIS", "ZELDA GILROY", "MAYNARD G KREBS", "ELLIOT NESS", "MR WILSON", "HAZEL BURKE", "JAMES KILDARE", "LEONARD GILLESPIE", "ROB PETRIE", "LAURA PETRIE", "ALAN BRADY", "BUDDY SORREL", "SALLY RODGERS", "JERRY HALPER", "MILLIE HALPER", "MEL COOLIE", "JED CLAMPETT", "GRANNY CLAMPETT", "ELLY MAY CLAMPETT", "JETHRO BODINE", "MILBURN DRYSDALE", "JANE HATHAWAY", "UNCLE MARTIN", "HERMAN MUNSTER", "LILY MUNSTER", "SAMANTHA STEVENS", "DARREN STEVENS", "ENDORA", "SERGEANT CARTER", "GOMEZ ADDAMS", "MORTICIA ADDAMS", "PUGSLEY ADDAMS", "WEDNESDAY ADDAMS", "LURCH", "UNCLE FESTER", "GRAND MA MA", "GILLIGAN", "GINGER GRANT", "THE SKIPPER", "THE PROFESSOR", "MARY ANN", "THURSTON HOWELL III", "BATMAN", "ROBIN", "ALFRED", "AUNT HARRIET", "MAXWELL SMART", "MR WAVERLY", "NAPOLEON SOLO", "ILYA KURYAKIN", "JAMES WEST", "ARTEMIS GORDON", "JEANNIE", "ANTHONY NELSON", "UNCLE BILL", "JOE FRIDAY", "BILL GANNON", "ROBERT T IRONSIDE", "EVE WHITFIELD", "MARK SANGER", "SGT ED BROWN", "ALEXANDER MUNDY", "DAN BRIGGS", "JIM PHELPS", "ROLLIN HAND", "WILLY ARMSTRONG", "BARNEY COLLIER", "CINNAMON CARTER", "MARCUS WELBY", "STEVE MCGARRET", "DAN WILLIAMS", "KONO", "CHIN HO KELLY", "WO FAT", "JOE MANNIX", "ARCHIE BUNKER", "EDITH BUNKER", "MEATHEAD", "FRED SANFORD", "LAMONT SANFORD", "AUNT ESTHER", "MARY RICHARDS", "TED KNIGHT", "LOU GRANT", "BARNABY JONES", "THEO KOJAK", "GEORGE JEFFERSON", "LOUISE JEFFERSON", "JIM ROCKFORD", "STEVE AUSTIN", "BARNEY MILLER", "NICK YEMANA", "RON HARRIS", "STANLEY WOJCIEHOWICZ", "INSPECTOR LUGER", "ARTHUR DIETRICH"]
      },
  { 
    cat: "U.S. Cities",
    sel: false,
    parent: "",
    numOfItems: 0,
    items: ["MOBILE", "ANCHORAGE", "SCOTTSDALE", "LOS ANGELES", "SAN DIEGO", "SAN FRANCISCO", "SAN JOSE", "BOULDER", "ASPEN", "VAIL", "DURANGO", "BETHLEHEM", "NEW LONDON", "NEW HAVEN", "WILMINGTON", "MIAMI", "TAMPA BAY", "ORLANDO", "AUGUSTA", "HILO", "CHICAGO", "PEORIA", "GARY", "LEXINGTON", "NEW ORLEANS", "BANGOR", "PORTLAND", "KENNEBUNKPORT", "BALTIMORE", "SPRINGFIELD", "ANN ARBOR", "MINNEAPOLIS", "BILOXI", "KANSAS CITY", "ST LOUIS", "RENO", "LAS VEGAS", "MANCHESTER", "MORRISTOWN", "PARAMUS", "ALBUQUERQUE", "NEW YORK CITY", "SYRACUSE", "CHARLOTTE", "COLUMBUS", "CINCINNATI", "CLEVELAND", "PITTSBURGH", "PHILADELPHIA", "NEWPORT", "CHARLESTON", "NASHVILLE", "MEMPHIS", "HOUSTON", "DALLAS", "EL PASO", "PROVO", "ALEXANDRIA", "ROANOKE", "SEATTLE", "TACOMA", "WHEELING", "GREEN BAY", "MILWAUKEE", "JACKSON HOLE", "SAN ANTONIO", "JACKSONVILLE", "FORT WORTH", "DETROIT", "LOUISVILLE", "FRESNO", "TUCSON", "OMAHA", "COLORADO SPRINGS", "VIRGINIA BEACH", "WICHITA", "ANAHEIM", "CORPUS CHRISTI", "NEWARK", "GREENSBORO", "JERSEY CITY", "BUFFALO", "TOLEDO", "ST PETERSBURG", "NORFOLK", "TACOMA", "ROCHESTER", "YONKERS", "FAYETTEVILLE", "NEWPORT NEWS", "TEMPE", "SHREVEPORT", "FORT LAUDERDALE", "FARGO", "ALLENTOWN", "WATERBURY", "WOODBRIDGE", "NEW BEDFORD"]
    },    
  { 
  
    cat: "World Capitals",
    sel: true,
    parent: "",
    numOfItems: 0,
    items: ["KABUL", "TIRANA", "ALGIERS", "ANDORRA LA VELLA", "LUANDA", "BUENOS AIRES", "YEREVAN", "CANBERRA", "VIENNA", "BAKU", "NASSAU", "DHAKA", "MINSK", "BRUSSELS", "LA PAZ", "SARAJEVO", "BRASILIA", "SOFIA", "PHNOM PENH", "OTTAWA", "SANTIAGO", "BEIJING", "BOGOTA", "KINSHASA", "BRAZZAVILLE", "SAN JOSE", "ZAGREB", "HAVANA", "NICOSIA", "PRAGUE", "COPENHAGEN", "SANTO DOMINGO", "QUITO", "CAIRO", "SAN SALVADOR", "TALLINN", "ADDIS ABABA","HELSINKI", "PARIS", "TBILISI", "BERLIN", "ATHENS", "GUATEMALA CITY", "PORT AU PRINCE", "BUDAPEST", "REYKJAVIK", "NEW DELHI", "JAKARTA", "TEHRAN", "BAGHAD", "DUBLIN", "JERUSALEM", "ROME", "KINGSTON", "TOKYO", "AMMAN", "NAIROBI", "PRISTINA", "KUWAIT CITY", "VIENTIANE", "RIGA", "BEIRUT", "MONROVIA", "TRIPOLI", "VADUZ", "VILNIUS", "LUXEMBOURG", "KUALA LUMPUR", "MEXICO CITY", "ULAANBAATAR", "RABAT", "KATHMANDU", "AMSTERDAM", "WELLINGTON", "MANAGUA", "PYONGYANG", "OSLO", "MUSCAT", "ISLAMABAD", "PANAMA CITY", "ASUNCION", "LIMA", "MANILA", "WARSAW", "LISBON", "BUCHAREST", "MOSCOW", "RIYADH", "DAKAR", "EDINBURGH", "BELGRADE", "BRATISLAVA", "LJUBLJANA", "MOGADISHU", "CAPE TOWN", "SEOUL", "MADRID", "KHARTOUM", "STOCKHOLM", "BERN", "DAMASCUS", "TAIPEI", "BANGKOK", "TUNIS", "ANKARA", "KAMPALA", "KYIV", "KIEV", "ABU DHABI", "LONDON", "WASHINGTON DC", "MONTEVIDEO", "TASHKENT","CARACAS", "HANOI"]
  },  
  { 
    cat: "World Cities",
    sel: false,
    parent: "",
    numOfItems: 0,
    items: ["RIO DE JANEIRO", "MELBOURNE", "SYDNEY", "ADELAIDE", "PERTH", "INNSBRUCK", "SALZBURG", "GHENT", "BRUGES", "SAO PAOLO", "MONTREAL", "QUEBEC", "TORONTO", "CALGARY", "WINNIPEG", "VANCOUVER", "SHANGHAI", "ALEXANDRIA", "MARSEILLE", "MUNICH", "POTSDAM", "DUSSELDORF", "HAMBURG", "FRANKFURT", "MUMBAI", "CALCUTTA", "TEL AVIV", "BETHLEHEM", "FLORENCE", "MILAN", "VENICE", "YOKOHAMA", "KYOTO", "OSAKA", "ACAPULCO", "CASABLANCA", "ROTTERDAM", "THE HAGUE", "CHRISTCHURCH", "KARACHI", "ISTANBUL", "KHARKOV", "LVIV", "LVOV", "MANCHESTER", "LIVERPOOL", "OXFORD", "CAMBRIDGE", "ABERDEEN", "GLASGOW", "ZURICH", "GENEVA", "INTERLAKEN", "LUCERNE", "BARCELONA", "ALEXANDRIA", "SAINT PETERSBURG", "SAPPORO", "DAMASCUS", "NAPLES", "MECCA", "HIROSHIMA", "TURIN", "AUKLAND", "ANTWERP"]
    }
]



   
const headerTextEl = document.getElementsByTagName("h1");
const btn = document.getElementById("test")
const scaffoldEl = document.querySelector(".scaffold");

let rCat = 0;
let rItem = 0;


if (headerTextEl){
  console.log("we have header text " + btn)
}

const hangmanTextEl = document.getElementById("hangman-text");

if (hangmanTextEl){
console.log("hangman text = " + hangmanTextEl.innerText)
}


let r = 0;
let picNum = 0;


let lineWork = [];


/*
btnReplace.addEventListener("click", () => {
  let regex = /[a-zA-Z0-9]/g;
  let result = myString.replace(regex, "#");
  output.innerText = result;
});
*/

initHangman();


function initHangman(){
  let category = JSON.parse(window.localStorage.getItem('hangmanCat'));
  if (category === "random" || !category){
    rCat = Math.floor(Math.random()*cats.length)
  } else {
    rCat = category 
  }

  rItem = Math.floor(Math.random()*cats[rCat].items.length)
  testLine = cats[rCat].items[rItem];
  console.log("hangman solution is " + testLine)
  let regex = /[a-zA-Z]/g;
  testLine = testLine.replace(regex, "-");
  lineWork = testLine.split('');
  hangmanTextEl.innerText = testLine;

  const allAlready = document.querySelectorAll('.already-clicked');

  allAlready.forEach((element) => {
    element.classList.remove('already-clicked');
  });
  picNum = 0;
  scaffoldEl.style.backgroundImage = "";

  $(document).ready(function() {
    $(".cs-text").lettering('words').children('span').lettering()
  });

  
$(document).ready(function() {
  $(".alpha").lettering('words').children('span').lettering()
});



}


btn.addEventListener("click", function () {
  console.log("clicked on header")

  let category = JSON.parse(window.localStorage.getItem('hangmanCat'));
  if (category === "random" || !category){
    rCat = Math.floor(Math.random()*cats.length)
  } else {
    rCat = category 
  }


console.log("rcat ritem = " + rCat + " " + rItem)

rItem = Math.floor(Math.random()*cats[rCat].items.length)

  testLine = cats[rCat].items[rItem];
  console.log("hangman solution is " + testLine)
  let regex = /[a-zA-Z]/g;
  testLine = testLine.replace(regex, "-");
  lineWork = testLine.split('');
  console.log("lineWork in event listener = " + lineWork)
  hangmanTextEl.innerText = testLine;



  const allAlready = document.querySelectorAll('.already-clicked');

  allAlready.forEach((element) => {
    element.classList.remove('already-clicked');
  });
  picNum = 0;
  scaffoldEl.style.backgroundImage = "";





   
  $(document).ready(function() {
    $(".cs-text").lettering('words').children('span').lettering()
  });
});



addKeyboardClicks();


function addKeyboardClicks(){    
  keyboardClicks = true;
  const keys = document.querySelectorAll(".alpha");
  for (let i = 0; i < keys.length; i++) {
    console.log("keys length = " + keys.length + "i = " + i)
    keys[i].addEventListener("click", ({ target }) => {
      console.log("target = " + target)
      let key = target.innerText;
      console.log ("key = " + key)
      target.blur() 

// If already clicked, no need to check again - just return
      if (target.classList.contains("already-clicked")){
        return;
      };

      found = findAllLetters(key);
      target.classList.add("already-clicked")

      if (found){
        const audio = new Audio ("./auds/shortgood.mp3");
        audio.play(); 
        } else {
        const audio = new Audio ("./auds/pop39222.mp3");
        audio.play();   
        picNum++;
        let pic = `url(../imgs/hang${picNum}.png)`
        scaffoldEl.style.backgroundImage = pic;
        if (picNum === 8){  
        console.log("You lose")  
        const audio = new Audio ("./auds/pop39222.mp3");
        audio.play(); 
        }
        
      }
    

      let text = lineWork.join("")
      hangmanTextEl.innerText = text;

      if (text === cats[rCat].items[rItem]){
        console.log("we have a winner")
        const audio = new Audio ("./auds/shortgood.mp3");
        audio.play(); 
      }


      console.log("text after finding letters = " + hangmanTextEl.innerText)
   $(document).ready(function() {
    $(".cs-text").lettering('words').children('span').lettering()
  });

/*
      if (key === "enter") {
        const audio = new Audio ("./auds/hard-keypress.wav");
        audio.play()
        handleSubmitWord();
        return;
      }

      if (key === "del") {
        const audio = new Audio ("./auds/hard-keypress.wav");
        audio.play()
        handleDelete();
        return;
      }

      if (key === "space") {
        const audio = new Audio ("./auds/keypress2.wav");
        audio.play()
        key = " "
      }*/
      const audio = new Audio ("./auds/keypress2.wav");
      audio.play()
 //     updateGuessedLetters(key);
    });
  }  // END OF FOR KEYBOARD LOOP




} // END OF Ians addKeyboardClicks 


function findAllLetters(key){
  console.log("loop thru line in original array and when a match with key is found, put the key into the appropriate index of testLine, then redisplay ")
  let found = false;
  for (i=0; i<cats[rCat].items[rItem].length; i++){
    if (key === cats[rCat].items[rItem][i].toUpperCase()){
       lineWork[i] = cats[rCat].items[rItem][i]
       found = true;
    }
  }
  return found;

}